In [1]:
import numpy as np

In [2]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [9]:
arr_3d = arr_2d.reshape(2, 1, 3)
print(arr_3d)

[[[1 2 3]]

 [[4 5 6]]]


In [4]:
print(arr_3d.shape)

(2, 1, 3)


In [5]:
print(arr_2d.reshape(-1))

[1 2 3 4 5 6]


In [6]:
print(arr_3d)

[[[1 2 3]]

 [[4 5 6]]]


In [8]:
arr_2d_new = arr_3d.reshape((3, 2))
print(arr_2d_new)

[[1 2]
 [3 4]
 [5 6]]


In [10]:
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr_3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [12]:
arr_flat1 = arr_3d.reshape(-1)
print(arr_flat1)

[1 2 3 4 5 6 7 8]


In [13]:
arr_flat2 = arr_3d.ravel()
print(arr_flat2)

[1 2 3 4 5 6 7 8]
