In [1]:
import numpy as np

In [2]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(arr1)

[[1 2]
 [3 4]]


In [3]:
print(arr2)

[[5 6]
 [7 8]]


In [4]:
res_v = np.concatenate((arr1, arr2), axis=0)
print(res_v)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [5]:
res_h = np.concatenate((arr1, arr2), axis=1)
print(res_h)

[[1 2 5 6]
 [3 4 7 8]]


In [6]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(arr1)
print(arr2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [7]:
print(np.vstack((arr1, arr2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [8]:
print(np.hstack((arr1, arr2)))

[[1 2 5 6]
 [3 4 7 8]]


In [9]:
print(np.vstack(arr1, arr2))

TypeError: vstack() takes 1 positional argument but 2 were given