In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [3]:
res_v = np.split(arr, 2, axis=0)
print(res_v)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [4]:
print(res_v[0])
print(res_v[1])

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [5]:
arr_h = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print(arr_h)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [6]:
res_h = np.split(arr_h, 2, axis=1)
print(res_h)

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])]


In [7]:
print(res_h[0])
print(res_h[1])

[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]


In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [9]:
res = np.split(arr, [1, 3], axis=0)
print(res)

[array([[1, 2, 3]]), array([[4, 5, 6],
       [7, 8, 9]]), array([[10, 11, 12]])]


In [10]:
print(res[0])
print(res[1])
print(res[2])

[[1 2 3]]
[[4 5 6]
 [7 8 9]]
[[10 11 12]]


In [11]:
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [12]:
print(np.vsplit(arr, 2))

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]


In [13]:
print(np.hsplit(arr, 2))

ValueError: array split does not result in an equal division

In [14]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [15]:
print(np.hsplit(arr, 2))

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])]
