In [1]:
import torch

In [2]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cuda


In [3]:
t = torch.randn(3, 4)
t

tensor([[ 0.2214,  0.7683, -1.0545, -1.2464],
        [ 1.1366,  1.1584,  0.5309, -0.8024],
        [ 0.0961,  0.9131, -0.1858,  1.2548]])

In [4]:
print(t.device)

cpu


In [5]:
t_gpu = t.to(device)
t_gpu

tensor([[ 0.2214,  0.7683, -1.0545, -1.2464],
        [ 1.1366,  1.1584,  0.5309, -0.8024],
        [ 0.0961,  0.9131, -0.1858,  1.2548]], device='cuda:0')

In [6]:
print(t_gpu.device)

cuda:0


In [7]:
t_direct = torch.randn(3, 4, device=device)

t_direct

tensor([[-1.9121, -1.0919,  0.7403, -1.1595],
        [-1.1150,  1.1442, -0.9346, -0.1164],
        [-0.7169, -0.3179, -0.6401,  0.3274]], device='cuda:0')

In [8]:
print(t_direct.device)

cuda:0


In [9]:
import torch.nn as nn

model = nn.Linear(10, 5)
model

Linear(in_features=10, out_features=5, bias=True)

In [11]:
model = model.to(device)

In [12]:
model

Linear(in_features=10, out_features=5, bias=True)

In [13]:
x = torch.randn(32, 10).to(device)

output = model(x)

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = nn.Linear(784, 10).to(device)

for inputs, labels in dataloader:
    # 每个 batch 的数据也要移到 GPU
    inputs = inputs.to(device)
    labels = labels.to(device)

    outputs = model(inputs)
    # ... 计算 loss，反向传播