In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
view_slice = arr[:2, :2]
print(view_slice)

[[1 2]
 [4 5]]


In [4]:
view_slice[0, 0] = 99
print(view_slice)

[[99  2]
 [ 4  5]]


In [5]:
print(arr)

[[99  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [6]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr)

[1 2 3 4 5 6]


In [7]:
print(arr.shape)

(6,)


In [8]:
view_reshape = arr.reshape(2, 3)
print(view_reshape)

[[1 2 3]
 [4 5 6]]


In [9]:
print(view_reshape.shape)

(2, 3)


In [10]:
view_reshape[1, 1] = 88
print(view_reshape)

[[ 1  2  3]
 [ 4 88  6]]


In [11]:
print(arr)

[ 1  2  3  4 88  6]


In [12]:
arr = np.array([[10, 20], [30, 40]])
print(arr)

[[10 20]
 [30 40]]


In [13]:
print(arr.shape)

(2, 2)


In [14]:
view_T = arr.T
print(view_T)

[[10 30]
 [20 40]]


In [15]:
view_T[0, 1] = 66
print(view_T)

[[10 66]
 [20 40]]


In [16]:
print(arr)

[[10 20]
 [66 40]]


In [18]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
view_slice = arr[:2, :2]

In [19]:
print(view_slice.base is arr)

True


In [20]:
print(arr.base)

None


In [21]:
print(view_slice.base)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
