In [1]:
import numpy as np

In [2]:
original = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(original)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
view_arr = original[:2, :2]
print(view_arr)

[[1 2]
 [4 5]]


In [4]:
copy_arr = original[:2, :2].copy()
print(copy_arr)

[[1 2]
 [4 5]]


In [5]:
print(view_arr.base)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
print(view_arr.base is original)

True


In [7]:
print(copy_arr.base)

None


In [8]:
print(original.base)

None


In [9]:
print(view_arr)

[[1 2]
 [4 5]]


In [10]:
print(original)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
view_arr[0, 0] = 99
print(view_arr)

[[99  2]
 [ 4  5]]


In [12]:
print(original)

[[99  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [13]:
print(copy_arr)

[[1 2]
 [4 5]]


In [14]:
print(original)

[[99  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [15]:
original = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(original)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
copy_arr = original[:2, :2].copy()
print(copy_arr)

[[1 2]
 [4 5]]


In [17]:
copy_arr[0, 0] = 88
print(copy_arr)

[[88  2]
 [ 4  5]]


In [18]:
print(original)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
print(original)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
view_arr = original[:2, :2]
print(view_arr)

[[1 2]
 [4 5]]


In [23]:
copy_arr = original[:2, :2].copy()
print(copy_arr)

[[1 2]
 [4 5]]


In [24]:
print(view_arr.flags.owndata)

False


In [25]:
print(copy_arr.flags.owndata)

True


In [26]:
print(original.flags.owndata)

True
