In [2]:
import numpy as np

In [3]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
copy_arr = arr[:2, :2].copy()
print(copy_arr)

[[1 2]
 [4 5]]


In [5]:
copy_arr[0, 0] = 99
print(copy_arr)

[[99  2]
 [ 4  5]]


In [6]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr)

[1 2 3 4 5 6]


In [8]:
copy_reshape = arr.copy().reshape(2, 3)
print(copy_reshape)

[[1 2 3]
 [4 5 6]]


In [9]:
copy_reshape[1, 1] = 88
print(copy_reshape)

[[ 1  2  3]
 [ 4 88  6]]


In [10]:
print(arr)

[1 2 3 4 5 6]


In [11]:
print(copy_arr.base)

None


In [15]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[:2, :2].base is arr)

True


In [16]:
print(arr[:2, :2].base)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
def process_data(arr):
    arr_copy = arr.copy()
    arr_copy[arr_copy > 5] = 0
    return arr_copy


raw_arr = np.array([[1, 6, 3], [8, 5, 9]])
print(raw_arr)

[[1 6 3]
 [8 5 9]]


In [18]:
process_arr = process_data(raw_arr)
print(process_arr)

[[1 0 3]
 [0 5 0]]


In [19]:
print(raw_arr)

[[1 6 3]
 [8 5 9]]
