In [23]:
import numpy as np

In [24]:
def my_func(x):
    return x * 2 if x > 3 else x + 10

In [25]:
print(my_func(3))

13


In [26]:
print(my_func(4))

8


In [27]:
print(my_func)

<function my_func at 0x00000235B469B880>


In [28]:
ufunc_my = np.frompyfunc(my_func, 1, 1)
print(ufunc_my)

<ufunc 'my_func (vectorized)'>


In [29]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [30]:
print(my_func(arr))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [31]:
res = ufunc_my(arr)

In [32]:
print(res)

[[11 12 13]
 [8 10 12]]


In [33]:
res = res.astype(float)
print(res)

[[11. 12. 13.]
 [ 8. 10. 12.]]


In [34]:
def calc(x, y):
    return x * y if x + y > 10 else x - y

In [35]:
print(calc(5, 6))

30


In [36]:
print(calc(1, 2))

-1


In [37]:
vec_calc = np.vectorize(calc)
print(vec_calc)

In [38]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([2, 4, 30])

In [39]:
res = vec_calc(arr1, arr2)
print(res)

[[ -1  -2  90]
 [  2   1 180]]
