In [6]:
import numpy as np

In [7]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [8]:
arr2 = np.array([[10, 20, 30], [40, 50, 60]])
print(arr2)

[[10 20 30]
 [40 50 60]]


In [9]:
scalar = 2
print(scalar)

2


In [10]:
print(arr1 + arr2)

[[11 22 33]
 [44 55 66]]


In [11]:
print(np.add(arr1, arr2))

[[11 22 33]
 [44 55 66]]


In [12]:
print(arr1 * scalar)

[[ 2  4  6]
 [ 8 10 12]]


In [13]:
print(np.multiply(arr1, scalar))

[[ 2  4  6]
 [ 8 10 12]]


In [14]:
print(arr1)

[[1 2 3]
 [4 5 6]]


In [15]:
print(arr1 ** 2)

[[ 1  4  9]
 [16 25 36]]


In [16]:
print(np.power(arr1, scalar))

[[ 1  4  9]
 [16 25 36]]


In [17]:
print(arr2 % arr1)

[[0 0 0]
 [0 0 0]]


In [18]:
print(np.mod(arr2, arr1))

[[0 0 0]
 [0 0 0]]


In [19]:
print(arr1)

[[1 2 3]
 [4 5 6]]


In [20]:
print(arr2)

[[10 20 30]
 [40 50 60]]


In [21]:
print(np.sqrt(arr1))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [22]:
print(np.sin(arr1))

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]


In [23]:
print(np.exp(arr1))

[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]


In [24]:
print(np.abs(np.array([-1, -2])))

[1 2]


In [25]:
print(arr1 > 3)

[[False False False]
 [ True  True  True]]


In [26]:
print(arr1)

[[1 2 3]
 [4 5 6]]


In [29]:
print(arr2)

[[10 20 30]
 [40 50 60]]


In [27]:
print(np.greater(arr1, 3))

[[False False False]
 [ True  True  True]]


In [28]:
print(arr1 == arr2 / 10)

[[ True  True  True]
 [ True  True  True]]


In [30]:
print(np.equal(arr1, arr2 / 10))

[[ True  True  True]
 [ True  True  True]]


In [31]:
print(arr2 <= 50)

[[ True  True  True]
 [ True  True False]]


In [32]:
print(np.less_equal(arr2, 50))

[[ True  True  True]
 [ True  True False]]


In [33]:
print(arr1)

[[1 2 3]
 [4 5 6]]


In [34]:
print(arr2)

[[10 20 30]
 [40 50 60]]


In [35]:
print((arr1 > 2) & (arr1 < 5))

[[False False  True]
 [ True False False]]


In [36]:
print((arr1 < 2) | (arr1 > 5))

[[ True False False]
 [False False  True]]


In [37]:
print(~(arr1 > 3))

[[ True  True  True]
 [False False False]]


In [38]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [39]:
print(arr1)

[1 2 3]


In [40]:
print(arr2)

[4 5 6]


In [41]:
out_arr = np.empty(3)
print(out_arr)

[ 2.15863353e-288  6.74038442e-312 -0.00000000e+000]


In [42]:
np.add(arr1, arr2, out=out_arr)

array([5., 7., 9.])

In [43]:
print(out_arr)

[5. 7. 9.]
