In [1]:
import numpy as np

In [2]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([10, 20, 30])

In [3]:
print(arr1)

[[1 2 3]
 [4 5 6]]


In [4]:
print(arr2)

[10 20 30]


In [5]:
scalar = 2

In [6]:
res_vec = np.multiply(arr1, scalar)
print(res_vec)

[[ 2  4  6]
 [ 8 10 12]]


In [7]:
res_broad = np.add(arr1, arr2)
print(res_broad)

[[11 22 33]
 [14 25 36]]


In [8]:
res_elem = np.sqrt(arr1)
print(res_elem)

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [9]:
import time

In [10]:
big_arr = np.random.rand(1000000)
print(big_arr)

[0.56869088 0.39474207 0.65311327 ... 0.06226774 0.84700425 0.54770655]


In [16]:
start = time.time()
ufunc_res = np.sin(big_arr)
print((time.time() - start) * 1000, "ms")

4.395246505737305 ms


In [12]:
print(ufunc_res)

[0.53852944 0.3845701  0.6076619  ... 0.06222751 0.74929989 0.52073064]


In [17]:
start = time.time()
loop_res = np.zeros_like(big_arr)
# print(loop_res)
for i in range(len(big_arr)):
    loop_res[i] = np.sin(big_arr[i])

print((time.time() - start) * 1000, "ms")

277.64415740966797 ms


In [15]:
print(loop_res)

[0.53852944 0.3845701  0.6076619  ... 0.06222751 0.74929989 0.52073064]
