In [1]:
import numpy as np
from sklearn.preprocessing import StandardScaler

In [2]:
data = np.array([
    [25, 8000],
    [30, 15000],
    [35, 20000],
    [45, 35000],
    [55, 50000],
])

data

array([[   25,  8000],
       [   30, 15000],
       [   35, 20000],
       [   45, 35000],
       [   55, 50000]])

In [3]:
scaler = StandardScaler()

data_scaled = scaler.fit_transform(data)

data_scaled

array([[-1.2070197 , -1.16702254],
       [-0.74278135, -0.70286585],
       [-0.27854301, -0.37132535],
       [ 0.64993368,  0.62329613],
       [ 1.57841037,  1.61791761]])

In [4]:
print("原始数据:")
print(data)
print("\n标准化后:")
print(np.round(data_scaled, 2))
print(f"\n均值: {scaler.mean_}")
print(f"标准差: {np.sqrt(scaler.var_)}")

原始数据:
[[   25  8000]
 [   30 15000]
 [   35 20000]
 [   45 35000]
 [   55 50000]]

标准化后:
[[-1.21 -1.17]
 [-0.74 -0.7 ]
 [-0.28 -0.37]
 [ 0.65  0.62]
 [ 1.58  1.62]]

均值: [   38. 25600.]
标准差: [1.07703296e+01 1.50811140e+04]


In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train, X_test = train_test_split(data, test_size=0.4, random_state=42)

In [7]:
X_train

array([[   35, 20000],
       [   25,  8000],
       [   45, 35000]])

In [8]:
X_test

array([[   30, 15000],
       [   55, 50000]])

In [9]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)