In [1]:
import numpy as np

In [3]:
print(np.arange(5))

[0 1 2 3 4]


In [4]:
print(np.arange(1, 5))

[1 2 3 4]


In [5]:
print(np.arange(1, 5, 2))

[1 3]


In [6]:
print(np.arange(0, 10, 2))

[0 2 4 6 8]


In [7]:
print(np.arange(0, 3, 0.5))

[0.  0.5 1.  1.5 2.  2.5]


In [8]:
print(np.linspace(0, 10, 5))

[ 0.   2.5  5.   7.5 10. ]


In [9]:
print(np.linspace(1, 3, 4))

[1.         1.66666667 2.33333333 3.        ]
