In [37]:
import numpy as np

In [38]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [39]:
print(np.ones(4))

[1. 1. 1. 1.]


In [40]:
print(np.full(3, 6))

[6 6 6]


In [41]:
print(np.full(3, 6.0))

[6. 6. 6.]


In [44]:
print(np.empty(12))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [45]:
print(np.zeros(5, dtype=int))

[0 0 0 0 0]


In [46]:
print(np.ones(5, dtype=int))

[1 1 1 1 1]
