In [1]:
import numpy as np

In [2]:
np.random.seed(666)

arr1 = np.array([[1, 2], [3, 4], [5, 6]])
print(arr1)

[[1 2]
 [3 4]
 [5 6]]


In [3]:
print(arr1)

[[1 2]
 [3 4]
 [5 6]]


In [19]:
np.random.shuffle(arr1)
print(arr1)

[[1 2]
 [5 6]
 [3 4]]


In [20]:
arr2 = np.array([10, 20, 30, 40])
print(arr2)

[10 20 30 40]


In [28]:
perm_arr = np.random.permutation(arr2)
print(perm_arr)

[20 10 40 30]


In [29]:
print(arr2)

[10 20 30 40]


In [30]:
arr3 = np.array([1, 2, 3, 4, 5])
print(arr3)

[1 2 3 4 5]


In [38]:
sample_no_replace = np.random.choice(arr3, size=3, replace=False)
print(sample_no_replace)

[1 3 2]


In [56]:
sample_replace = np.random.choice(arr3, size=5, replace=True)
print(sample_replace)

[1 1 5 3 1]


In [52]:
np.random.seed(666)

rand_sample = np.random.random_sample((2, 2))
print(rand_sample)

[[0.70043712 0.84418664]
 [0.67651434 0.72785806]]


In [67]:
weight_choice = np.random.choice([10, 20, 30], size=5, p=[0.1, 0.7, 0.2])
print(weight_choice)

[20 20 20 20 20]
