In [1]:
import numpy as np

In [2]:
np.random.seed(888)

print(np.random.randint(1, 10, (2, 2)))

[[7 4]
 [8 2]]


In [4]:
np.random.seed(888)

print(np.random.randint(1, 10, (2, 2)))

[[7 4]
 [8 2]]


In [5]:
print(np.random.randint(1, 10, (2, 2)))

[[1 1]
 [4 1]]


In [50]:
rng1 = np.random.default_rng(888)
rng2 = np.random.default_rng(999)

print(rng1.random((1, 2)))
print(rng2.random((1, 2)))

rng1_again = np.random.default_rng(888)
print(rng1_again.random((1, 2)))

[[0.39138063 0.02749503]]
[[0.77882502 0.17224863]]
[[0.39138063 0.02749503]]


[[0.68607168 0.51452038]]


In [22]:
print(np.__version__)

2.4.1


[[0.92081192 0.16227386]]


In [66]:
rng3 = np.random.default_rng()

print(rng3.integers(1, 10, (2, 2)))

[[7 3]
 [5 1]]


In [68]:
print(rng3.randint(1, 10, (2, 3)))

AttributeError: 'numpy.random._generator.Generator' object has no attribute 'randint'