In [1]:
import numpy as np

In [6]:
np.random.seed(666)

rand_arr = np.random.rand(2, 3)
print(rand_arr)

[[0.70043712 0.84418664 0.67651434]
 [0.72785806 0.95145796 0.0127032 ]]


In [12]:
rand_arr = np.random.rand(2, 3)
print(rand_arr)

[[0.36959638 0.07516654 0.77519298]
 [0.21940924 0.07934213 0.48678052]]


In [16]:
np.random.seed(666)

randn_arr = np.random.randn(2, 2)
print(randn_arr)

[[0.82418808 0.479966  ]
 [1.17346801 0.90904807]]


In [29]:
np.random.seed(666)

randint_arr = np.random.randint(1, 10, (3, 2))
print(randint_arr)

[[3 7]
 [5 4]
 [2 1]]


In [38]:
choice_arr = np.random.choice([10, 20, 30], size=(2, 2))
print(choice_arr)

[[30 10]
 [10 30]]


In [44]:
random_arr = np.random.random((1, 4))
print(random_arr)

[[0.44446092 0.95619151 0.73353358 0.71210247]]


In [45]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [49]:
np.random.shuffle(arr)

In [50]:
print(arr)

[3 5 4 2 1]
