In [1]:
import numpy as np

In [2]:
arr_1d = np.array([1, 2, 3])
print(arr_1d)

[1 2 3]


In [3]:
print(f"一维数组shape：{arr_1d.shape} → 仅axis=0")

一维数组shape：(3,) → 仅axis=0


In [4]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [5]:
print(f"二维数组shape：{arr_2d.shape} → axis0=行，axis1=列")

二维数组shape：(2, 3) → axis0=行，axis1=列


In [6]:
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(f"三维数组shape：{arr_3d.shape} → axis0=层，axis1=行，axis2=列")

三维数组shape：(2, 2, 2) → axis0=层，axis1=行，axis2=列


In [7]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [8]:
print(arr_2d.sum(axis=0))

[5 7 9]


In [9]:
print(arr_2d.sum(axis=1))

[ 6 15]


In [10]:
print(arr_2d.sum())

21
