In [1]:
import numpy as np

In [2]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [3]:
print("axis=0（列内求和）：", arr_2d.sum(axis=0))

axis=0（列内求和）： [15 18 21 24]


In [4]:
print("axis=1（行内求和）：", arr_2d.sum(axis=1))

axis=1（行内求和）： [10 26 42]


In [5]:
print("无axis（全局求和）：", arr_2d.sum())

无axis（全局求和）： 78


In [6]:
print("axis=0（列内最大值）：", arr_2d.max(axis=0))

axis=0（列内最大值）： [ 9 10 11 12]


In [7]:
print("axis=1（行内最大值）：", arr_2d.max(axis=1))

axis=1（行内最大值）： [ 4  8 12]


In [8]:
print("axis=0（列内均值）：", arr_2d.mean(axis=0))

axis=0（列内均值）： [5. 6. 7. 8.]


In [9]:
print("axis=1（行内均值）：", arr_2d.mean(axis=1))

axis=1（行内均值）： [ 2.5  6.5 10.5]


In [10]:
arr_3d = np.array(
    [
        [
            [1, 2],
            [3, 4],
            [5, 6]
        ],
        [
            [7, 8],
            [9, 10],
            [11, 12]
        ]
    ]
)
print(arr_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [11]:
print(arr_3d.sum(axis=0))

[[ 8 10]
 [12 14]
 [16 18]]


In [12]:
print(arr_3d.sum(axis=1))

[[ 9 12]
 [27 30]]


In [13]:
print(arr_3d.sum(axis=2))

[[ 3  7 11]
 [15 19 23]]
