In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3])

In [3]:
arr

array([1, 2, 3])

In [4]:
print(arr)

[1 2 3]


In [5]:
arr.ndim

1

In [6]:
arr.shape

(3,)

In [7]:
arr.size

3

In [9]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [10]:
arr2.ndim

2

In [11]:
arr2.shape

(2, 3)

In [12]:
arr2.size

6

In [13]:
arr3 = np.array([1, 2, "3"])

In [14]:
print(arr3)

['1' '2' '3']


In [15]:
arr3.dtype

dtype('<U21')

In [16]:
arr.dtype

dtype('int64')

In [18]:
arr2.dtype

dtype('int64')

In [19]:
tuple1 = (1,)
print(tuple1)

(1,)


In [20]:
tuple1 = (1)
print(tuple1)

1
