In [5]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures

In [6]:
X = np.array([[2], [3]])
X

array([[2],
       [3]])

In [7]:
poly2 = PolynomialFeatures(degree=2, include_bias=False)
X_poly2 = poly2.fit_transform(X)

In [8]:
print(f"\ndegree=2 特征：")
print(X_poly2)


degree=2 特征：
[[2. 4.]
 [3. 9.]]


In [10]:
poly3 = PolynomialFeatures(degree=3, include_bias=False)
X_poly3 = poly3.fit_transform(X)

print(f"\ndegree=3 特征：")
print(X_poly3)


degree=3 特征：
[[ 2.  4.  8.]
 [ 3.  9. 27.]]


In [11]:
X_multi = np.array([[1, 2], [3, 4]])
X_multi

array([[1, 2],
       [3, 4]])

In [12]:
poly2m = PolynomialFeatures(degree=2, include_bias=False)

X_poly_multi = poly2m.fit_transform(X_multi)

print(f"\n多特征 degree=2：")
print(f"特征名: {poly2m.get_feature_names_out()}")
print(X_poly_multi)


多特征 degree=2：
特征名: ['x0' 'x1' 'x0^2' 'x0 x1' 'x1^2']
[[ 1.  2.  1.  2.  4.]
 [ 3.  4.  9. 12. 16.]]


In [15]:
X_multi = np.array([[1, 2], [3, 4]])

poly2m = PolynomialFeatures(degree=2, include_bias=False, interaction_only=True)

X_poly_multi = poly2m.fit_transform(X_multi)

print(f"\n多特征 degree=2：")
print(f"特征名: {poly2m.get_feature_names_out()}")
print(X_poly_multi)


多特征 degree=2：
特征名: ['x0' 'x1' 'x0 x1']
[[ 1.  2.  2.]
 [ 3.  4. 12.]]


In [17]:
X_multi = np.array([[1, 2, 3], [4, 5, 6]])

poly2m = PolynomialFeatures(degree=2, include_bias=False)

X_poly_multi = poly2m.fit_transform(X_multi)

print(f"\n多特征 degree=2：")
print(f"特征名: {poly2m.get_feature_names_out()}")
print(X_poly_multi)


多特征 degree=2：
特征名: ['x0' 'x1' 'x2' 'x0^2' 'x0 x1' 'x0 x2' 'x1^2' 'x1 x2' 'x2^2']
[[ 1.  2.  3.  1.  2.  3.  4.  6.  9.]
 [ 4.  5.  6. 16. 20. 24. 25. 30. 36.]]
