In [1]:
import numpy as np

#### 案例1

In [2]:
sales = np.array([
    [100, 200, np.nan, 150],
    [300, -50, 250, 400],
    [np.nan, 180, 220, 190]
])
print(sales)

[[100. 200.  nan 150.]
 [300. -50. 250. 400.]
 [ nan 180. 220. 190.]]


In [3]:
sales_clean = sales.copy()
print(sales_clean)

[[100. 200.  nan 150.]
 [300. -50. 250. 400.]
 [ nan 180. 220. 190.]]


In [4]:
col_means = np.nanmean(sales_clean, axis=0)
print(col_means)

[200.         110.         235.         246.66666667]


In [5]:
for i in range(sales_clean.shape[1]):
    sales_clean[np.isnan(sales_clean[:, i]), i] = col_means[i]
print(sales_clean)

[[100. 200. 235. 150.]
 [300. -50. 250. 400.]
 [200. 180. 220. 190.]]


In [6]:
sales_clean[sales_clean < 0] = np.nanmean(sales_clean, axis=0)[1]
print(sales_clean)

[[100. 200. 235. 150.]
 [300. 110. 250. 400.]
 [200. 180. 220. 190.]]


In [7]:
print(sales_clean)

[[100. 200. 235. 150.]
 [300. 110. 250. 400.]
 [200. 180. 220. 190.]]


In [8]:
total_sales = np.nansum(sales_clean)
print(total_sales)

2535.0


In [9]:
avg_sales = np.nanmean(sales_clean)
print(avg_sales)

211.25


In [10]:
max_sales = np.nanmax(sales_clean)
print(max_sales)

400.0


#### 案例2

In [11]:
scores = np.array([
    [85, 90, 78],
    [92, 88, 95],
    [76, 80, 82]
])
print(scores)

[[85 90 78]
 [92 88 95]
 [76 80 82]]


In [12]:
mean = np.mean(scores, axis=0)
print(mean)

[84.33333333 86.         85.        ]


In [13]:
std = np.std(scores, axis=0)
print(std)

[6.5489609  4.3204938  7.25718035]


In [14]:
standardized = (scores - mean) / std
print(standardized)

[[ 0.10179732  0.9258201  -0.96456195]
 [ 1.17066918  0.46291005  1.37794564]
 [-1.2724665  -1.38873015 -0.41338369]]


#### 案例3

In [15]:
consume = np.array([50, 30, 80, 30, 50, 100, 80, 50, 20, 100])
print(consume)

[ 50  30  80  30  50 100  80  50  20 100]


In [16]:
unique_consume, counts = np.unique(consume, return_counts=True)
print(unique_consume)

[ 20  30  50  80 100]


In [17]:
print(counts)

[1 2 3 2 2]


In [18]:
sorted_index = np.argsort(unique_consume)[::-1]
sorted_consume = unique_consume[sorted_index]
print(sorted_consume)

[100  80  50  30  20]


In [20]:
sorted_counts = counts[sorted_index]
print(sorted_counts)

[2 2 3 2 1]


In [21]:
top3 = sorted_consume[:3]
print(top3)

[100  80  50]


In [22]:
ratings = np.array([
    [5, 3, np.nan, 1],
    [4, np.nan, 3, 2],
    [np.nan, 4, 2, 5],
    [2, 1, 5, 4]
])