In [1]:
import numpy as np

In [2]:
ratings = np.array([
    [5, 3, np.nan, 1],
    [4, np.nan, 3, 2],
    [np.nan, 4, 2, 5],
    [2, 1, 5, 4]
])

In [3]:
ratings_clean = ratings.copy()
print(ratings_clean)

[[ 5.  3. nan  1.]
 [ 4. nan  3.  2.]
 [nan  4.  2.  5.]
 [ 2.  1.  5.  4.]]


In [4]:
ratings_clean[np.isnan(ratings_clean)] = 0
print(ratings_clean)

[[5. 3. 0. 1.]
 [4. 0. 3. 2.]
 [0. 4. 2. 5.]
 [2. 1. 5. 4.]]


In [5]:
norm = np.linalg.norm(ratings_clean, axis=1, keepdims=True)
print(norm)

[[5.91607978]
 [5.38516481]
 [6.70820393]
 [6.78232998]]


In [6]:
normed_ratings = ratings_clean / norm
print(normed_ratings)

[[0.84515425 0.50709255 0.         0.16903085]
 [0.74278135 0.         0.55708601 0.37139068]
 [0.         0.59628479 0.2981424  0.74535599]
 [0.29488391 0.14744196 0.73720978 0.58976782]]


In [7]:
similarity = normed_ratings @ normed_ratings.T
print(similarity)

[[1.         0.6905413  0.42835974 0.42367807]
 [0.6905413  1.         0.44290923 0.8487578 ]
 [0.42835974 0.44290923 1.         0.74729787]
 [0.42367807 0.8487578  0.74729787 1.        ]]


In [8]:
np.fill_diagonal(similarity, 0)
print(similarity)

[[0.         0.6905413  0.42835974 0.42367807]
 [0.6905413  0.         0.44290923 0.8487578 ]
 [0.42835974 0.44290923 0.         0.74729787]
 [0.42367807 0.8487578  0.74729787 0.        ]]


In [9]:
max_index = np.unravel_index(np.argmax(similarity), similarity.shape)
print(max_index)

(np.int64(1), np.int64(3))


In [10]:
print(np.round(similarity, 2))

[[0.   0.69 0.43 0.42]
 [0.69 0.   0.44 0.85]
 [0.43 0.44 0.   0.75]
 [0.42 0.85 0.75 0.  ]]


In [11]:
print(f"用户{max_index[0] + 1} 和 用户{max_index[1] + 1}")

用户2 和 用户4


In [12]:
print(f"相似度 {similarity[max_index]:.2f}")

相似度 0.85


In [13]:
np.random.seed(42)
returns = np.random.randn(100, 5) * 0.01
print(returns)

[[ 4.96714153e-03 -1.38264301e-03  6.47688538e-03  1.52302986e-02
  -2.34153375e-03]
 [-2.34136957e-03  1.57921282e-02  7.67434729e-03 -4.69474386e-03
   5.42560044e-03]
 [-4.63417693e-03 -4.65729754e-03  2.41962272e-03 -1.91328024e-02
  -1.72491783e-02]
 [-5.62287529e-03 -1.01283112e-02  3.14247333e-03 -9.08024076e-03
  -1.41230370e-02]
 [ 1.46564877e-02 -2.25776300e-03  6.75282047e-04 -1.42474819e-02
  -5.44382725e-03]
 [ 1.10922590e-03 -1.15099358e-02  3.75698018e-03 -6.00638690e-03
  -2.91693750e-03]
 [-6.01706612e-03  1.85227818e-02 -1.34972247e-04 -1.05771093e-02
   8.22544912e-03]
 [-1.22084365e-02  2.08863595e-03 -1.95967012e-02 -1.32818605e-02
   1.96861236e-03]
 [ 7.38466580e-03  1.71368281e-03 -1.15648282e-03 -3.01103696e-03
  -1.47852199e-02]
 [-7.19844208e-03 -4.60638771e-03  1.05712223e-02  3.43618290e-03
  -1.76304016e-02]
 [ 3.24083969e-03 -3.85082280e-03 -6.76922000e-03  6.11676289e-03
   1.03099952e-02]
 [ 9.31280119e-03 -8.39217523e-03 -3.09212376e-03  3.31263431e-03

In [15]:
window = 5
print(returns.shape)

(100, 5)


In [16]:
roll_mean = np.array([np.mean(returns[i: i + window], axis=0) for i in range(len(returns) - window + 1)])

In [18]:
print(roll_mean.shape)

(96, 5)


In [19]:
print(roll_mean)

[[ 1.40504149e-03 -5.26777320e-04  4.07772215e-03 -6.38499407e-03
  -6.74639518e-03]
 [ 6.33458359e-04 -2.55223587e-03  3.53374111e-03 -1.06323312e-02
  -6.86147593e-03]
 [-1.01680951e-04 -2.00610513e-03  1.97187720e-03 -1.18088043e-02
  -6.30150619e-03]
 [-1.61653287e-03 -6.56918437e-04 -2.43138759e-03 -1.06386159e-02
  -2.45794806e-03]
 [ 9.84975353e-04  1.71148037e-03 -3.29117882e-03 -9.42477510e-03
  -2.59038463e-03]
 [-3.38601060e-03  1.24175542e-03 -1.31199077e-03 -5.88804215e-03
  -5.02769950e-03]
 [-2.95968784e-03  2.77357802e-03 -3.41723081e-03 -3.46341219e-03
  -2.38231295e-03]
 [ 1.06285620e-04 -2.60941340e-03 -4.00866111e-03 -6.85463469e-04
  -2.07631252e-03]
 [ 1.58962444e-03 -3.39845854e-03 -2.30199081e-03 -4.21504620e-04
  -8.44983347e-04]
 [ 2.82517134e-03 -3.88521535e-03 -6.36284521e-05  9.03974822e-04
   8.21821124e-04]
 [ 4.98765097e-03  1.12135329e-04 -2.24952498e-03  3.34602555e-03
  -8.91588773e-04]
 [ 5.98328804e-03  1.05639403e-03 -1.49369568e-03  2.30619453e-03

In [20]:
returns_copy = returns.copy()
print(returns_copy)

[[ 4.96714153e-03 -1.38264301e-03  6.47688538e-03  1.52302986e-02
  -2.34153375e-03]
 [-2.34136957e-03  1.57921282e-02  7.67434729e-03 -4.69474386e-03
   5.42560044e-03]
 [-4.63417693e-03 -4.65729754e-03  2.41962272e-03 -1.91328024e-02
  -1.72491783e-02]
 [-5.62287529e-03 -1.01283112e-02  3.14247333e-03 -9.08024076e-03
  -1.41230370e-02]
 [ 1.46564877e-02 -2.25776300e-03  6.75282047e-04 -1.42474819e-02
  -5.44382725e-03]
 [ 1.10922590e-03 -1.15099358e-02  3.75698018e-03 -6.00638690e-03
  -2.91693750e-03]
 [-6.01706612e-03  1.85227818e-02 -1.34972247e-04 -1.05771093e-02
   8.22544912e-03]
 [-1.22084365e-02  2.08863595e-03 -1.95967012e-02 -1.32818605e-02
   1.96861236e-03]
 [ 7.38466580e-03  1.71368281e-03 -1.15648282e-03 -3.01103696e-03
  -1.47852199e-02]
 [-7.19844208e-03 -4.60638771e-03  1.05712223e-02  3.43618290e-03
  -1.76304016e-02]
 [ 3.24083969e-03 -3.85082280e-03 -6.76922000e-03  6.11676289e-03
   1.03099952e-02]
 [ 9.31280119e-03 -8.39217523e-03 -3.09212376e-03  3.31263431e-03

In [21]:
std = np.std(returns_copy)
print(std)

0.009802715029966269


In [22]:
extremes = returns_copy[(returns_copy > 2 * std) | (returns_copy < -2 * std)]
print(extremes)

[-0.02619745 -0.01987569  0.02463242  0.02190456  0.02720169  0.03852731
  0.02314659  0.02143944 -0.02025143  0.02122156 -0.03241267  0.02133033
  0.02092387  0.02153182  0.02189803 -0.02123896  0.02060748 -0.02039232
 -0.02067442  0.01964725 -0.02301921  0.03078881]


In [23]:
unique_extremes = np.unique(extremes)

In [24]:
print(unique_extremes)

[-0.03241267 -0.02619745 -0.02301921 -0.02123896 -0.02067442 -0.02039232
 -0.02025143 -0.01987569  0.01964725  0.02060748  0.02092387  0.02122156
  0.02133033  0.02143944  0.02153182  0.02189803  0.02190456  0.02314659
  0.02463242  0.02720169  0.03078881  0.03852731]


In [25]:
weekly_returns = returns.reshape(-1, 5, 5).sum(axis=1)
print(weekly_returns)

[[ 0.00702521 -0.00263389  0.02038861 -0.03192497 -0.03373198]
 [-0.01693005  0.00620878 -0.00655995 -0.02944021 -0.0251385 ]
 [ 0.02493825  0.00056068 -0.01124762  0.01673013 -0.00445794]
 [-0.01265964  0.02624327  0.0106664  -0.01278818 -0.0290949 ]
 [-0.01837512  0.00494927  0.0012621   0.01659487  0.00910698]
 [ 0.03199009 -0.01635035 -0.04878603  0.02093336 -0.02096897]
 [-0.01915274  0.03005557  0.02772095 -0.01683968  0.01435957]
 [ 0.02105654 -0.00398377  0.00677632 -0.01816508  0.0001207 ]
 [ 0.03064481 -0.00428705  0.03000281  0.00122162  0.01769735]
 [-0.00134519 -0.02334086 -0.00994061  0.00602519  0.0288066 ]
 [-0.02478558  0.02321797 -0.02093758  0.00022086 -0.01848072]
 [-0.02277499  0.01116004  0.01292052  0.00775443  0.02111665]
 [-0.00811349  0.03093371 -0.00147349  0.04387531 -0.00053776]
 [-0.01963663 -0.01769038 -0.00616416 -0.00865498  0.00355255]
 [-0.00548986  0.03711673  0.01923977  0.01621439  0.0122407 ]
 [-0.02824266 -0.00606531 -0.00030744  0.04331391  0.00

In [26]:
print(np.round(roll_mean[:3], 4))

[[ 0.0014 -0.0005  0.0041 -0.0064 -0.0067]
 [ 0.0006 -0.0026  0.0035 -0.0106 -0.0069]
 [-0.0001 -0.002   0.002  -0.0118 -0.0063]]


In [27]:
print(np.round(unique_extremes, 4))

[-0.0324 -0.0262 -0.023  -0.0212 -0.0207 -0.0204 -0.0203 -0.0199  0.0196
  0.0206  0.0209  0.0212  0.0213  0.0214  0.0215  0.0219  0.0219  0.0231
  0.0246  0.0272  0.0308  0.0385]


In [28]:
print(np.round(weekly_returns[0], 4))

[ 0.007  -0.0026  0.0204 -0.0319 -0.0337]
