In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
arr[arr > 5] = 0
print(arr)

[[1 2 3]
 [4 5 0]
 [0 0 0]]


In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [5]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
arr[(arr > 3) & (arr < 7)] = 99
print(arr)

[[ 1  2  3]
 [99 99 99]
 [ 7  8  9]]


In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [8]:
new_arr = np.where(arr % 2 == 0, -1, arr)
print(new_arr)

[[ 1 -1  3]
 [-1  5 -1]]


In [9]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
conditions = [arr < 3, (arr >= 3) & (arr <= 6), arr]
values = [10, 20]

new_arr = np.select(conditions, values, default=30)

In [13]:
print(new_arr)

[[10 10 20]
 [20 20 20]
 [30 30 30]]


In [14]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
arr[arr < 3] = np.nan

ValueError: cannot convert float NaN to integer