In [1]:
import numpy as np
from adodbapi.apibase import adoRowIdTypes

In [2]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [3]:
res1 = np.where(arr % 2 == 0, -1, arr)
print(res1)

[[ 1 -1  3]
 [-1  5 -1]]


In [4]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [5]:
res2 = np.where((arr > 3) & (arr < 6), 99, 0)
print(res2)

[[ 0  0  0]
 [99 99  0]]


In [6]:
res3 = np.where(arr > 3, arr * 2, arr)
print(res3)

[[ 1  2  3]
 [ 8 10 12]]


In [7]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
rows, cols = np.where(arr > 5)
print(rows)
print(cols)

[1 2 2 2]
[2 0 1 2]


In [10]:
print(arr[rows, cols])

[6 7 8 9]


In [11]:
arr_1d = np.array([10, 20, 30, 40])
print(arr_1d)

[10 20 30 40]


In [12]:
index = np.where(arr_1d == 30)
print(index)

(array([2]),)


In [13]:
print(arr_1d[index])

[30]


In [14]:
print(arr_1d)

[10 20 30 40]
