In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [3]:
bool_arr = arr > 3
print(bool_arr)

[[False False False]
 [ True  True  True]]


In [4]:
filter_arr = arr[bool_arr]
print(filter_arr)

[4 5 6]


In [5]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [6]:
print(arr[arr % 2 == 0])

[2 4 6]


In [7]:
print(arr[arr <= 2])

[1 2]


In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
print(arr[(arr > 3) & (arr < 7)])

[4 5 6]


In [10]:
print(arr[(arr < 3) | (arr > 7)])

[1 2 8 9]


In [11]:
print(arr[~(arr > 5)])

[1 2 3 4 5]


In [12]:
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)
print(arr)

[[1. 2. 3.]
 [4. 5. 6.]]


In [13]:
arr[arr < 3] = np.nan
print(arr)

[[nan nan  3.]
 [ 4.  5.  6.]]
