In [1]:
import numpy as np

In [2]:
arr = np.array([10, 20, 30, 40, 50, 60])
print(arr)

[10 20 30 40 50 60]


In [3]:
print(arr[1: 4])

[20 30 40]


In [4]:
print(arr[: 3])

[10 20 30]


In [5]:
print(arr[3:])

[40 50 60]


In [6]:
print(arr)

[10 20 30 40 50 60]


In [7]:
print(arr[::2])

[10 30 50]


In [8]:
print(arr[1:5:2])

[20 40]


In [10]:
print(arr)

[10 20 30 40 50 60]


In [9]:
print(arr[::-1])

[60 50 40 30 20 10]


In [11]:
print(arr[5:1:-2])

[60 40]


In [12]:
arr = np.array([10, 20, 30, 40, 50])
print(arr)

[10 20 30 40 50]


In [13]:
print(arr[1:4])

[20 30 40]


In [14]:
arr[1:4] = 99
print(arr)

[10 99 99 99 50]


In [15]:
arr[::2] = 0
print(arr)

[ 0 99  0 99  0]


In [16]:
arr = np.array([10, 20, 30, 40, 50])
print(arr)

[10 20 30 40 50]


In [17]:
print(arr[-4:-1])

[20 30 40]


In [18]:
print(arr.shape)

(5,)


In [19]:
print(arr[1: 100])

[20 30 40 50]


In [20]:
print(arr[1:4:0])

ValueError: slice step cannot be zero

In [21]:
print(arr)

[10 20 30 40 50]


In [22]:
arr1 = arr[1:4]
print(arr1)

[20 30 40]


In [23]:
print(arr)
print(arr1)

[10 20 30 40 50]
[20 30 40]


In [24]:
arr1[1] = 999

In [25]:
print(arr1)

[ 20 999  40]


In [26]:
print(arr)

[ 10  20 999  40  50]
