In [1]:
import numpy as np

In [2]:
arr = np.array([10, 20, 30, 40, 50])
print(arr)

[10 20 30 40 50]


In [3]:
print(arr[0])
print(arr[2])

10
30


In [4]:
print(arr[-1])

50


In [5]:
print(arr[-3])

30


In [6]:
print(arr)

[10 20 30 40 50]


In [7]:
arr[0] = 100
print(arr)

[100  20  30  40  50]


In [8]:
arr

array([100,  20,  30,  40,  50])

In [9]:
arr[-1] = 500
print(arr)

[100  20  30  40 500]


In [10]:
print(arr[5])

IndexError: index 5 is out of bounds for axis 0 with size 5

In [11]:
arr[0] = 'a'

ValueError: invalid literal for int() with base 10: 'a'