In [1]:
import numpy as np

In [2]:
arr = np.array([10, 20, 30, 40, 50, 60])
print(arr)

[10 20 30 40 50 60]


In [3]:
print(arr[[0, 2, 5]])

[10 30 60]


In [4]:
print(arr[[1, -1, -3]])

[20 60 40]


In [5]:
print(arr)

[10 20 30 40 50 60]


In [6]:
index = np.array([4, 0, 2])
print(index)

[4 0 2]


In [7]:
print(arr[index])

[50 10 30]


In [9]:
arr = np.array([10, 20, 30, 40, 50])
print(arr)

[10 20 30 40 50]


In [10]:
arr[[0, 2, 4]] = 999
print(arr)

[999  20 999  40 999]


In [11]:
print(arr)

[999  20 999  40 999]


In [12]:
arr[[1, 3]] = [88, 77]
print(arr)

[999  88 999  77 999]


In [13]:
print(arr)

[999  88 999  77 999]


In [14]:
print(arr[[0, 6]])

IndexError: index 6 is out of bounds for axis 0 with size 5