In [1]:
import numpy as np

In [2]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [3]:
arr_1d = np.array([1, 2, 3])
print(arr_1d)

[1 2 3]


In [4]:
print(arr_2d.ndim)

2


In [5]:
print(arr_1d.ndim)

1


In [6]:
print(arr_2d.shape)

(2, 3)


In [7]:
arr_2d_tuple = np.array(((10, 20), (30, 40), (50, 60)))
print(arr_2d_tuple)

[[10 20]
 [30 40]
 [50 60]]


In [8]:
print(arr_2d_tuple.shape)

(3, 2)


In [9]:
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr_3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [10]:
print(arr_3d.ndim)

3


In [11]:
print(arr_3d.shape)

(2, 2, 2)


In [12]:
print(np.array([[1, 2], [3]]))

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.