In [1]:
import numpy as np

In [2]:
arr_1d = np.array([1, 2, 3, 4, 5, 6])
print(arr_1d)

[1 2 3 4 5 6]


In [3]:
arr_2d = arr_1d.reshape((2, 3))
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [4]:
arr_3d = arr_1d.reshape((2, 1, 3))
print(arr_3d)

[[[1 2 3]]

 [[4 5 6]]]


In [5]:
print(arr_1d.shape)

(6,)


In [6]:
print(arr_2d.shape)

(2, 3)


In [7]:
print(arr_3d.shape)

(2, 1, 3)


In [8]:
print(arr_1d)

[1 2 3 4 5 6]


In [9]:
arr_1d = np.array([1, 2, 3, 4, 5, 6])
print(arr_1d)

[1 2 3 4 5 6]


In [10]:
arr_1d.resize((3, 2))

In [11]:
print(arr_1d)

[[1 2]
 [3 4]
 [5 6]]


In [12]:
arr_1d = np.array([1, 2, 3, 4, 5, 6])
print(arr_1d)

[1 2 3 4 5 6]


In [13]:
arr_2d = arr_1d.reshape(-1, 3)
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [14]:
print(arr_2d.shape)

(2, 3)


In [15]:
arr_2d = arr_1d.reshape(3, -1)
print(arr_2d)

[[1 2]
 [3 4]
 [5 6]]


In [16]:
print(arr_2d.shape)

(3, 2)
