In [1]:
import numpy as np

In [10]:
np.random.seed(666)

rand_2d = np.random.rand(2, 3)
print(rand_2d)

[[0.70043712 0.84418664 0.67651434]
 [0.72785806 0.95145796 0.0127032 ]]


In [24]:
np.random.seed(666)

randint_2d = np.random.randint(1, 10, (3, 2))
print(randint_2d)

[[3 7]
 [5 4]
 [2 1]]


In [27]:
np.random.seed(666)

normal_2d = np.random.normal(size=(2, 2))
print(normal_2d)

[[0.82418808 0.479966  ]
 [1.17346801 0.90904807]]


In [31]:
np.random.seed(666)

randint_3d = np.random.randint(0, 5, (2, 3, 2))
print(randint_3d)

[[[4 2]
  [1 4]
  [3 3]]

 [[4 4]
  [1 0]
  [0 2]]]
