In [1]:
import numpy as np

In [2]:
zero_2d = np.zeros((2, 3))
print(zero_2d)

[[0. 0. 0.]
 [0. 0. 0.]]


In [4]:
one_2d = np.ones((3, 2), dtype=int)
print(one_2d)

[[1 1]
 [1 1]
 [1 1]]


In [5]:
full_2d = np.full((2, 2), 99)
print(full_2d)

[[99 99]
 [99 99]]


In [6]:
eye_2d = np.eye(3)
print(eye_2d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
zero_3d = np.zeros((2, 3, 2))
print(zero_3d)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [12]:
print(zero_3d.shape)

(2, 3, 2)


In [13]:
print(np.zeros(2, 3))

TypeError: Cannot interpret '3' as a data type