In [1]:
import torch
import torch.nn as nn

In [2]:
gru = nn.GRU(input_size=10, hidden_size=20, num_layers=1, batch_first=True)

In [3]:
gru

GRU(10, 20, batch_first=True)

In [4]:
x = torch.randn(3, 5, 10)

In [5]:
x

tensor([[[-0.8644,  1.2701, -2.5588, -0.8673, -2.1641, -0.3344,  0.6299,
          -0.9337, -1.3348,  0.3708],
         [-0.4238, -0.3511,  0.8684,  1.4116,  1.8756, -1.7960, -1.7136,
           0.7172,  0.7262,  0.0632],
         [-0.5828, -0.3608,  0.5012, -0.6950,  1.7307,  2.3053,  0.1893,
          -1.2672, -1.7406, -0.9899],
         [-0.2633,  0.2306,  0.2436,  1.4197,  0.2220, -0.2742,  0.5487,
           2.6211,  0.3692,  0.0896],
         [-0.3421, -1.9063, -1.0602,  0.9802,  1.3210,  0.3786, -1.2601,
          -0.0088, -0.4021, -0.3654]],

        [[-1.4877,  0.3626,  0.2944,  0.5396, -0.8834,  1.0321, -0.6917,
           0.5514, -0.3339, -0.2410],
         [-1.3333,  1.6321,  0.3306, -1.1378, -0.7761,  0.5475,  1.0669,
           0.1935, -0.5865,  1.8142],
         [ 0.3884,  0.8294, -0.3204, -0.2986,  1.5847,  0.2857, -0.1592,
           1.5225,  0.3063,  2.0775],
         [-2.2748, -1.4554,  0.3271, -0.3885, -0.0417, -0.6563,  0.6807,
          -0.2969, -0.2743,  0.5921],

In [6]:
output, h_n = gru(x)

In [7]:
output

tensor([[[-0.2043, -0.2406,  0.2377, -0.1212,  0.1774, -0.3183,  0.0698,
           0.3753,  0.1867,  0.2111, -0.0160, -0.2036,  0.1253, -0.1768,
          -0.3655,  0.3535, -0.2721,  0.2843, -0.0063, -0.2900],
         [-0.1965, -0.0959,  0.1309,  0.0046,  0.0754,  0.0449,  0.1016,
           0.1706, -0.0328,  0.2795,  0.1509,  0.2893, -0.0063,  0.1268,
           0.0964, -0.2153,  0.0244, -0.0093,  0.0322,  0.0761],
         [ 0.2726,  0.2117, -0.0480,  0.0634,  0.1197, -0.1295, -0.0691,
          -0.0502, -0.0121,  0.3047,  0.0530,  0.3076, -0.2496,  0.0424,
           0.2433, -0.3086,  0.1327,  0.0404,  0.2061, -0.2176],
         [ 0.1654,  0.1814,  0.1902,  0.1723, -0.0409,  0.0810,  0.0904,
           0.0344, -0.0577,  0.0954, -0.0189,  0.3604,  0.0770, -0.0664,
           0.2314,  0.0845, -0.1999, -0.1950,  0.3028,  0.3820],
         [ 0.0389,  0.2231,  0.2569,  0.3381, -0.0801, -0.0043,  0.2190,
           0.0247, -0.3666,  0.3838,  0.0580,  0.4017,  0.0200,  0.0401,
          

In [8]:
h_n

tensor([[[ 0.0389,  0.2231,  0.2569,  0.3381, -0.0801, -0.0043,  0.2190,
           0.0247, -0.3666,  0.3838,  0.0580,  0.4017,  0.0200,  0.0401,
           0.3250, -0.0842,  0.0483, -0.2729,  0.0533,  0.3812],
         [-0.3913, -0.0553,  0.2683,  0.0110,  0.1660, -0.3866,  0.0095,
           0.4176,  0.0158,  0.4400, -0.1239, -0.0843, -0.1551,  0.0515,
           0.2437,  0.3055, -0.3068,  0.2858,  0.2521, -0.4058],
         [-0.1288, -0.1958,  0.1061,  0.3078,  0.1562,  0.0484, -0.1216,
          -0.0851, -0.1331,  0.2246, -0.1273,  0.1195, -0.0211,  0.0594,
          -0.0496,  0.1698,  0.4899, -0.1895,  0.3712,  0.4582]]],
       grad_fn=<StackBackward0>)

In [9]:
print(f"输出形状: {output.shape}")

输出形状: torch.Size([3, 5, 20])


In [10]:
print(f"隐藏状态: {h_n.shape}")

隐藏状态: torch.Size([1, 3, 20])


In [11]:
gru_2layer = nn.GRU(input_size=10, hidden_size=20, num_layers=2, batch_first=True)

In [12]:
output, h_n = gru_2layer(x)

In [13]:
print(f"多层隐藏状态: {h_n.shape}")

多层隐藏状态: torch.Size([2, 3, 20])
