In [1]:
import torch
import torch.nn as nn

In [2]:
lstm = nn.LSTM(input_size=10, hidden_size=20, num_layers=1, batch_first=True)

In [3]:
lstm

LSTM(10, 20, batch_first=True)

In [4]:
x = torch.randn(3, 5, 10)

In [5]:
x

tensor([[[-6.4708e-01, -5.6410e-01, -5.4617e-01, -7.1783e-02,  3.6606e-01,
           2.0647e-01, -4.0146e-01, -9.3718e-01,  6.2755e-01, -2.8446e-01],
         [ 3.9989e-01, -2.8734e-01,  1.2491e+00, -1.1365e-01,  2.3760e+00,
          -1.0768e-01, -8.4792e-01,  1.5278e-02, -1.2322e-01,  6.3365e-01],
         [ 1.1177e+00, -1.9000e-01, -1.9236e+00, -5.5748e-01, -6.2963e-01,
          -4.6676e-01,  1.0878e+00, -9.9064e-01, -2.3528e-01,  5.6157e-01],
         [-1.5637e+00, -5.2378e-01, -4.9034e-02, -6.2483e-01,  1.9024e-01,
           8.2548e-01,  2.0214e+00, -1.0306e+00, -2.0987e-01, -7.4826e-01],
         [ 6.7647e-01,  1.3552e+00, -1.7930e+00,  1.5666e+00, -1.5583e+00,
          -4.6080e-01, -1.1925e+00,  1.0264e-02, -9.0913e-01, -1.2176e-03]],

        [[-6.4566e-01, -5.0841e-01, -1.6638e+00, -1.5903e+00,  1.4718e+00,
          -8.4958e-01, -8.1615e-02,  1.0031e+00,  1.1015e-02, -2.0532e+00],
         [ 4.0459e-01, -1.0914e+00, -9.1642e-01, -6.0575e-01,  4.1516e-01,
          -9.7122

In [6]:
output, (h_n, c_n) = lstm(x)

In [7]:
output

tensor([[[ 5.4327e-02,  2.5613e-02,  3.4114e-02, -6.6284e-02, -3.9159e-05,
           3.2463e-02,  2.7817e-02, -5.6595e-02, -1.2086e-01, -1.2667e-01,
           3.2941e-02, -9.6635e-02,  1.0980e-01, -2.9462e-02, -1.0981e-01,
           5.1681e-02,  4.4980e-02, -5.7670e-02, -7.6249e-02, -6.6054e-02],
         [ 2.1042e-01,  8.0913e-02, -3.3227e-02, -1.4204e-01, -7.6283e-02,
           1.0008e-01,  1.1871e-01,  7.7635e-02,  3.2458e-03, -1.5718e-01,
           4.9914e-03, -2.8186e-01,  1.9166e-01,  1.0863e-01,  1.8641e-01,
           1.0032e-01, -7.2822e-02,  4.1006e-02, -6.8568e-03, -4.3062e-02],
         [ 1.5108e-01,  6.6444e-02,  2.2813e-02, -2.6708e-02, -1.8592e-01,
          -2.1347e-02,  2.3426e-01, -1.2666e-01, -6.4591e-02, -1.8567e-01,
           5.6254e-02, -4.3346e-02,  4.8097e-02, -3.0866e-02,  4.7082e-02,
           3.6855e-02, -2.3225e-02, -1.3479e-01, -9.7175e-02, -5.7314e-02],
         [ 1.0964e-01,  1.1490e-01,  1.3927e-01, -1.1189e-01,  6.7509e-03,
          -7.5640e-02,

In [8]:
h_n

tensor([[[ 0.0289, -0.0611,  0.0583,  0.0770, -0.1036,  0.1685,  0.1164,
          -0.0934, -0.1232, -0.1049,  0.1877,  0.0114,  0.0310, -0.0097,
           0.0027, -0.1033, -0.0177, -0.1127, -0.0152, -0.2021],
         [ 0.0979,  0.0838,  0.0091, -0.0842, -0.0296,  0.0535,  0.1723,
          -0.0422,  0.1791, -0.0758,  0.0129, -0.2971,  0.1875,  0.2006,
           0.2840,  0.1160, -0.0753, -0.0191, -0.0659, -0.0050],
         [ 0.1503,  0.1341,  0.0273, -0.0253, -0.0700,  0.0729,  0.2573,
          -0.1727, -0.0445, -0.1224,  0.0799, -0.1860,  0.1010,  0.1024,
           0.2828,  0.1298, -0.2577, -0.0473, -0.0138, -0.1172]]],
       grad_fn=<StackBackward0>)

In [9]:
c_n

tensor([[[ 0.1213, -0.2992,  0.1385,  0.1934, -0.2073,  0.3585,  0.2818,
          -0.1983, -0.2231, -0.1938,  0.3211,  0.0393,  0.0591, -0.0188,
           0.0061, -0.2080, -0.0557, -0.1698, -0.0283, -0.4791],
         [ 0.1924,  0.1517,  0.0182, -0.2004, -0.0648,  0.0821,  0.4554,
          -0.0740,  0.3104, -0.1591,  0.0435, -0.4881,  0.3235,  0.4062,
           0.4139,  0.2968, -0.1393, -0.0585, -0.1075, -0.0124],
         [ 0.3214,  0.3288,  0.0719, -0.0349, -0.1201,  0.1603,  0.4841,
          -0.2872, -0.1047, -0.2124,  0.2253, -0.4332,  0.2549,  0.2204,
           0.4787,  0.2225, -0.5900, -0.0799, -0.0242, -0.2491]]],
       grad_fn=<StackBackward0>)

In [10]:
print(f"输出形状: {output.shape}")

输出形状: torch.Size([3, 5, 20])


In [11]:
print(f"隐藏状态 h_n: {h_n.shape}")

隐藏状态 h_n: torch.Size([1, 3, 20])


In [12]:
print(f"细胞状态 c_n: {c_n.shape}")

细胞状态 c_n: torch.Size([1, 3, 20])


In [13]:
h_0 = torch.zeros(1, 3, 20)
c_0 = torch.zeros(1, 3, 20)

In [14]:
output, (h_n, c_n) = lstm(x, (h_0, c_0))

In [15]:
output

tensor([[[ 5.4327e-02,  2.5613e-02,  3.4114e-02, -6.6284e-02, -3.9159e-05,
           3.2463e-02,  2.7817e-02, -5.6595e-02, -1.2086e-01, -1.2667e-01,
           3.2941e-02, -9.6635e-02,  1.0980e-01, -2.9462e-02, -1.0981e-01,
           5.1681e-02,  4.4980e-02, -5.7670e-02, -7.6249e-02, -6.6054e-02],
         [ 2.1042e-01,  8.0913e-02, -3.3227e-02, -1.4204e-01, -7.6283e-02,
           1.0008e-01,  1.1871e-01,  7.7635e-02,  3.2458e-03, -1.5718e-01,
           4.9914e-03, -2.8186e-01,  1.9166e-01,  1.0863e-01,  1.8641e-01,
           1.0032e-01, -7.2822e-02,  4.1006e-02, -6.8568e-03, -4.3062e-02],
         [ 1.5108e-01,  6.6444e-02,  2.2813e-02, -2.6708e-02, -1.8592e-01,
          -2.1347e-02,  2.3426e-01, -1.2666e-01, -6.4591e-02, -1.8567e-01,
           5.6254e-02, -4.3346e-02,  4.8097e-02, -3.0866e-02,  4.7082e-02,
           3.6855e-02, -2.3225e-02, -1.3479e-01, -9.7175e-02, -5.7314e-02],
         [ 1.0964e-01,  1.1490e-01,  1.3927e-01, -1.1189e-01,  6.7509e-03,
          -7.5640e-02,