In [1]:
import torch
import torch.nn as nn

In [2]:
rnn = nn.RNN(input_size=10, hidden_size=20, num_layers=1, batch_first=True)

In [3]:
rnn

RNN(10, 20, batch_first=True)

In [4]:
x = torch.randn(3, 5, 10)
x

tensor([[[-2.0911e+00, -8.4197e-01,  1.3940e-01,  7.8939e-01, -1.0706e-01,
           1.6992e+00, -7.2657e-01, -2.4087e-02,  7.1961e-01,  3.1470e-01],
         [-9.5229e-01, -8.8807e-02, -2.5606e-01,  3.9118e-01, -3.0737e-01,
          -1.5030e-01, -8.2330e-01, -2.1919e+00,  1.1536e+00, -9.0138e-01],
         [ 3.2616e-01,  4.8206e-01,  4.7729e-02, -1.0733e+00, -2.0795e-02,
          -3.3046e+00, -4.8874e-01, -1.1810e-01, -2.6784e-01, -1.3486e+00],
         [ 3.5362e-01,  2.3221e+00,  1.2161e-01, -2.0438e+00,  9.5882e-01,
           2.8144e-02,  1.4078e+00,  1.0752e+00,  1.1477e+00, -1.9209e+00],
         [-4.9690e-01,  1.9153e+00, -2.5200e-01,  6.5769e-01, -3.3851e-01,
          -3.9409e-01, -8.5629e-01, -9.6878e-01, -1.0330e+00,  5.2885e-01]],

        [[ 2.2716e+00,  1.1046e-01,  1.1783e-01,  7.7203e-03,  2.1349e+00,
          -1.6959e+00,  1.1875e-01, -2.3632e-02,  3.8204e-02,  1.3901e+00],
         [-1.8419e+00,  2.1148e-01,  2.5989e-01,  1.3408e+00,  2.2307e+00,
           8.4462

In [5]:
output, h_n = rnn(x)

In [6]:
output

tensor([[[-0.4152, -0.4726,  0.2430, -0.3504, -0.2916,  0.1789,  0.4411,
          -0.5526,  0.2257,  0.5096,  0.3389, -0.0270, -0.0806,  0.3024,
          -0.4334,  0.0739,  0.2214,  0.1173, -0.1114,  0.0530],
         [-0.1697,  0.4398, -0.2844, -0.2003,  0.5889, -0.3384, -0.4702,
           0.2781,  0.7740,  0.1828, -0.1295, -0.1264, -0.5366,  0.0800,
          -0.6386,  0.5626, -0.2764, -0.2464,  0.1414, -0.5403],
         [ 0.6643,  0.6037, -0.2717,  0.2620,  0.5866, -0.7388, -0.5155,
           0.4125,  0.3559, -0.7091, -0.3477,  0.4709, -0.7130,  0.2629,
          -0.2626,  0.7487, -0.7704,  0.4371,  0.2314, -0.2170],
         [-0.1912,  0.0914,  0.1638, -0.2262,  0.0223, -0.1563, -0.7414,
           0.0389,  0.2974, -0.6833,  0.0121, -0.6508, -0.1561,  0.0074,
          -0.7190, -0.0512, -0.1825,  0.6176, -0.7305, -0.5712],
         [ 0.3806,  0.8366,  0.2133, -0.0685,  0.5657,  0.0047,  0.0491,
          -0.1086,  0.6576,  0.5382, -0.2123, -0.3729, -0.7562, -0.1038,
          

In [7]:
h_n

tensor([[[ 0.3806,  0.8366,  0.2133, -0.0685,  0.5657,  0.0047,  0.0491,
          -0.1086,  0.6576,  0.5382, -0.2123, -0.3729, -0.7562, -0.1038,
          -0.5262,  0.6911, -0.4204,  0.0632,  0.7704, -0.0084],
         [-0.1215,  0.4427,  0.3646, -0.6016,  0.0429, -0.2266, -0.1730,
           0.1635, -0.1959,  0.0938,  0.6376, -0.3942, -0.1109, -0.2512,
           0.2678, -0.1823,  0.3682,  0.6204,  0.4726, -0.3247],
         [-0.3774,  0.1779, -0.4477, -0.3750,  0.6191, -0.3352, -0.7260,
           0.0064,  0.7219, -0.1584,  0.0197, -0.5724, -0.6926, -0.1433,
          -0.2706,  0.0492, -0.5762, -0.0245, -0.2175, -0.2333]]],
       grad_fn=<StackBackward0>)

In [8]:
print(f"输出形状: {output.shape}")

输出形状: torch.Size([3, 5, 20])


In [9]:
print(f"最终隐藏状态: {h_n.shape}")

最终隐藏状态: torch.Size([1, 3, 20])


In [10]:
rnn_2layer = nn.RNN(input_size=10, hidden_size=20, num_layers=2, batch_first=True)
rnn_2layer

RNN(10, 20, num_layers=2, batch_first=True)

In [11]:
x

tensor([[[-2.0911e+00, -8.4197e-01,  1.3940e-01,  7.8939e-01, -1.0706e-01,
           1.6992e+00, -7.2657e-01, -2.4087e-02,  7.1961e-01,  3.1470e-01],
         [-9.5229e-01, -8.8807e-02, -2.5606e-01,  3.9118e-01, -3.0737e-01,
          -1.5030e-01, -8.2330e-01, -2.1919e+00,  1.1536e+00, -9.0138e-01],
         [ 3.2616e-01,  4.8206e-01,  4.7729e-02, -1.0733e+00, -2.0795e-02,
          -3.3046e+00, -4.8874e-01, -1.1810e-01, -2.6784e-01, -1.3486e+00],
         [ 3.5362e-01,  2.3221e+00,  1.2161e-01, -2.0438e+00,  9.5882e-01,
           2.8144e-02,  1.4078e+00,  1.0752e+00,  1.1477e+00, -1.9209e+00],
         [-4.9690e-01,  1.9153e+00, -2.5200e-01,  6.5769e-01, -3.3851e-01,
          -3.9409e-01, -8.5629e-01, -9.6878e-01, -1.0330e+00,  5.2885e-01]],

        [[ 2.2716e+00,  1.1046e-01,  1.1783e-01,  7.7203e-03,  2.1349e+00,
          -1.6959e+00,  1.1875e-01, -2.3632e-02,  3.8204e-02,  1.3901e+00],
         [-1.8419e+00,  2.1148e-01,  2.5989e-01,  1.3408e+00,  2.2307e+00,
           8.4462

In [14]:
x.shape

torch.Size([3, 5, 10])

In [12]:
output, h_n = rnn_2layer(x)

In [13]:
print(f"隐藏状态形状: {h_n.shape}")

隐藏状态形状: torch.Size([2, 3, 20])
