In [1]:
import numpy as np

In [3]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [4]:
print(arr_2d[0:2, :])

[[1 2 3 4]
 [5 6 7 8]]


In [5]:
print(arr_2d[:, 1:3])

[[ 2  3]
 [ 6  7]
 [10 11]]


In [6]:
print(arr_2d[1:3, 2:4])

[[ 7  8]
 [11 12]]


In [7]:
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [8]:
print(arr_2d[::2, ::2])

[[ 1  3]
 [ 9 11]]


In [9]:
print(arr_2d[-2:, -3:])

[[ 6  7  8]
 [10 11 12]]


In [10]:
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
arr_2d[1:3, 1:3] = 99

In [12]:
print(arr_2d)

[[ 1  2  3  4]
 [ 5 99 99  8]
 [ 9 99 99 12]]


In [13]:
print(arr_2d)

[[ 1  2  3  4]
 [ 5 99 99  8]
 [ 9 99 99 12]]


In [14]:
print(arr_2d[1: 100])

[[ 5 99 99  8]
 [ 9 99 99 12]]
