In [1]:
import numpy as np

In [2]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [3]:
print(arr_2d[[0, 2], [1, 3]])

[ 2 12]


In [4]:
print(arr_2d[[1, 0], :])

[[5 6 7 8]
 [1 2 3 4]]


In [5]:
print(arr_2d[:, [3, 1]])

[[ 4  2]
 [ 8  6]
 [12 10]]


In [6]:
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
arr_2d[[0, 2], [0, 2]] = 999

In [8]:
print(arr_2d)

[[999   2   3   4]
 [  5   6   7   8]
 [  9  10 999  12]]


In [9]:
print(arr_2d)

[[999   2   3   4]
 [  5   6   7   8]
 [  9  10 999  12]]


In [10]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
bool_arr = arr_2d > 5

In [12]:
print(bool_arr)

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]


In [13]:
print(arr_2d[bool_arr])

[ 6  7  8  9 10 11 12]


In [14]:
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
arr_2d[arr_2d % 2 == 0] = 0
print(arr_2d)

[[ 1  0  3  0]
 [ 5  0  7  0]
 [ 9  0 11  0]]


In [16]:
print(arr_2d)

[[ 1  0  3  0]
 [ 5  0  7  0]
 [ 9  0 11  0]]


In [17]:
print(arr_2d[[0, 1], [2]])

[3 7]
