In [1]:
import numpy as np

In [2]:
arr_3d = np.array(
    [
        [
            [1, 2],
            [3, 4],
            [5, 6]
        ],
        [
            [7, 8],
            [9, 10],
            [11, 12]
        ]
    ]
)
print(arr_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [3]:
print(arr_3d[1, 2, 1])

12


In [4]:
print(arr_3d[0, -1, 0])

5


In [5]:
print(arr_3d[0])

[[1 2]
 [3 4]
 [5 6]]


In [6]:
print(arr_3d[1, 1])

[ 9 10]


In [7]:
print(arr_3d[0, :, 1])

[2 4 6]


In [8]:
print(arr_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [10]:
print(arr_3d[0:2, :, :])

[[[1 2]
  [3 4]
  [5 6]]]


In [11]:
print(arr_3d[:, 1:3, :])

[[[ 3  4]
  [ 5  6]]

 [[ 9 10]
  [11 12]]]


In [12]:
print(arr_3d[::1, ::2, ::1])

[[[ 1  2]
  [ 5  6]]

 [[ 7  8]
  [11 12]]]


In [13]:
print(arr_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [14]:
arr_3d[1, 1:3, 0] = 99

In [15]:
print(arr_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [99 10]
  [99 12]]]


In [16]:
print(arr_3d.shape)

(2, 3, 2)
