In [1]:
import numpy as np

In [2]:
arr_2d = np.array([[10, 20, 30], [40, 50, 60]])
print(arr_2d)

[[10 20 30]
 [40 50 60]]


In [3]:
print(arr_2d[0, 1])

20


In [4]:
print(arr_2d[1, -1])

60


In [5]:
print(arr_2d[1][0])

40


In [6]:
print(arr_2d)

[[10 20 30]
 [40 50 60]]


In [7]:
print(arr_2d[0])

[10 20 30]


In [8]:
print(arr_2d[1])

[40 50 60]


In [9]:
print(arr_2d[-1])

[40 50 60]


In [10]:
print(arr_2d[:, 1])

[20 50]


In [11]:
print(arr_2d[:, -1])

[30 60]


In [12]:
print(arr_2d)

[[10 20 30]
 [40 50 60]]


In [13]:
arr_2d[1, 2] = 600

In [14]:
print(arr_2d)

[[ 10  20  30]
 [ 40  50 600]]


In [15]:
arr_2d[0] = [1, 2, 3]

In [16]:
print(arr_2d)

[[  1   2   3]
 [ 40  50 600]]


In [17]:
arr_2d[:, 0] = [100, 200]
print(arr_2d)

[[100   2   3]
 [200  50 600]]
