In [1]:
import numpy as np

In [2]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [3]:
scalar = 2

In [4]:
print("乘法：\n", arr_2d * scalar)

乘法：
 [[ 2  4  6]
 [ 8 10 12]]


In [5]:
print("加法：\n", arr_2d + scalar)

加法：
 [[3 4 5]
 [6 7 8]]


In [7]:
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [6]:
print("大于3: \n", arr_2d > 3)

大于3: 
 [[False False False]
 [ True  True  True]]


In [8]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[10, 20, 30], [40, 50, 60]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [9]:
print(arr2)

[[10 20 30]
 [40 50 60]]


In [10]:
print("数组相加: \n", arr1 + arr2)

数组相加: 
 [[11 22 33]
 [44 55 66]]


In [11]:
print("数组相乘: \n", arr1 * arr2)

数组相乘: 
 [[ 10  40  90]
 [160 250 360]]


In [12]:
print("数组相等: \n", arr1 == arr2)

数组相等: 
 [[False False False]
 [False False False]]


In [14]:
import numpy as np
import time

arr = np.random.randint(0, 100, (1000, 1000))
print(arr)

[[40  7  7 ... 92 62 29]
 [56 11  6 ... 58 68 17]
 [59  0 65 ...  9 45 64]
 ...
 [49 68 94 ... 54 85 79]
 [ 7  5 15 ... 59  2 94]
 [59 96 68 ... 62 75 32]]


In [15]:
print(arr.shape)

(1000, 1000)


In [18]:
start = time.time()
res_vec = arr * 2
print("向量化耗时：", (time.time() - start) * 1000, "ms")

向量化耗时： 0.92315673828125 ms


In [19]:
start = time.time()
res_loop = np.zeros_like(arr)
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        res_loop[i, j] = arr[i, j] * 2

print("循环耗时：", (time.time() - start) * 1000, "ms")

循环耗时： 246.88220024108887 ms
