In [1]:
import numpy as np

In [2]:
arr_a = np.array([[1, 2, 3], [4, 5, 6]])
arr_b = np.array([[7, 8], [9, 10], [11, 12]])

In [3]:
print(arr_a)

[[1 2 3]
 [4 5 6]]


In [4]:
print(arr_b)

[[ 7  8]
 [ 9 10]
 [11 12]]


In [5]:
res_dot = np.dot(arr_a, arr_b)
print("np.dot结果（2行2列）：\n", res_dot)

np.dot结果（2行2列）：
 [[ 58  64]
 [139 154]]


In [6]:
res_at = arr_a @ arr_b
print("@运算符结果：\n", res_at)

@运算符结果：
 [[ 58  64]
 [139 154]]


In [7]:
print(arr_a @ arr_a)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [9]:
import numpy as np

# 同形数组（2行2列）
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# 1. 逐元素乘（向量化运算）
print("逐元素乘 * ：\n", arr1 * arr2)  # 输出：# [[ 5 12]#  [21 32]]

# 2. 矩阵乘法 @
print("矩阵乘法 @ ：\n", arr1 @ arr2)  # 输出：# [[19 22]#  [43 50]]

逐元素乘 * ：
 [[ 5 12]
 [21 32]]
矩阵乘法 @ ：
 [[19 22]
 [43 50]]


In [10]:
print(arr1)

[[1 2]
 [3 4]]


In [11]:
print(arr2)

[[5 6]
 [7 8]]


In [12]:
arr_2d = np.array([[1, 2], [3, 4], [5, 6]])
print(arr_2d)

[[1 2]
 [3 4]
 [5 6]]


In [13]:
arr_1d = np.array([7, 8])
print(arr_1d)

[7 8]


In [15]:
print(arr_2d @ arr_1d)

[23 53 83]
