In [1]:
import numpy as np

In [3]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [4]:
print("转置结果（3行2列）：\n", arr.T)

转置结果（3行2列）：
 [[1 4]
 [2 5]
 [3 6]]


In [5]:
print(np.transpose(arr))

[[1 4]
 [2 5]
 [3 6]]


In [6]:
arr = np.array([[1, 2], [3, 4]])
print(arr)

[[1 2]
 [3 4]]


In [7]:
inv_arr = np.linalg.inv(arr)
print("逆矩阵：\n", inv_arr)

逆矩阵：
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [8]:
print(arr @ inv_arr)

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [9]:
print(np.linalg.inv(np.array([[1, 2], [3, 4], [5, 6]])))

LinAlgError: Last 2 dimensions of the array must be square

In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
print(arr.trace())

15
