In [1]:
import torch

a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])
print(a)

tensor([1., 2., 3.])


In [2]:
print(b)

tensor([4., 5., 6.])


In [3]:
print(a + b)

tensor([5., 7., 9.])


In [4]:
print(a * b)

tensor([ 4., 10., 18.])


In [5]:
print(a / b)

tensor([0.2500, 0.4000, 0.5000])


In [6]:
print(a)

tensor([1., 2., 3.])


In [7]:
print(a * 2 + 1)

tensor([3., 5., 7.])


In [8]:
m1 = torch.randn(2, 3)
m2 = torch.randn(3, 2)

print(m1)

tensor([[ 0.3894, -0.1624, -0.3632],
        [ 1.4501,  1.6207,  0.5621]])


In [9]:
print(m2)

tensor([[-1.3889,  0.0570],
        [ 0.6522, -0.9562],
        [ 0.6608,  0.1213]])


In [10]:
result = m1 @ m2

print(result)

tensor([[-0.8867,  0.1334],
        [-0.5856, -1.3988]])


In [11]:
print(result.shape)

torch.Size([2, 2])


In [12]:
result2 = torch.mm(m1, m2)
print(result2)

tensor([[-0.8867,  0.1334],
        [-0.5856, -1.3988]])


In [13]:
batch_a = torch.randn(8, 2, 3)
batch_b = torch.randn(8, 3, 4)

batch_c = batch_a @ batch_b

In [14]:
print(batch_c)

tensor([[[ 1.4286, -0.7070,  0.2562,  0.5395],
         [ 0.1989,  0.6464,  1.3832, -1.7294]],

        [[-1.2298, -0.5358,  0.6959, -0.8947],
         [-0.9004,  1.1737,  0.6453,  0.4857]],

        [[-1.2336, -0.2899, -1.2720,  1.4423],
         [-0.6727, -0.4327,  0.8099, -0.2534]],

        [[ 0.0572,  0.1540,  1.4643, -0.0999],
         [-0.3240, -1.6221, -0.9657, -2.5652]],

        [[ 3.3877,  2.3384,  0.5061,  1.2283],
         [-0.1354, -1.0603,  0.0544,  0.4074]],

        [[ 2.8270,  0.2508,  0.0430, -1.2230],
         [-1.9302,  0.5680,  2.2893, -0.5332]],

        [[-2.7186,  0.1998, -1.4747, -1.0025],
         [-0.0619, -1.7305,  0.7773, -1.2799]],

        [[-0.2013,  0.0314,  1.5662, -0.7785],
         [ 1.2961,  0.6017, -2.2533, -0.0460]]])


In [15]:
print(batch_c.shape)

torch.Size([8, 2, 4])


In [16]:
t = torch.arange(12)
print(t)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [17]:
print(t.shape)

torch.Size([12])


In [18]:
t2 = t.reshape(3, 4)
print(t2)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [19]:
print(t2.shape)

torch.Size([3, 4])


In [20]:
t3 = t.view(4, 3)
print(t3)

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])


In [21]:
print(t3.shape)

torch.Size([4, 3])


In [22]:
t4 = t.reshape(-1, 4)
print(t4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [23]:
print(t4.shape)

torch.Size([3, 4])


In [24]:
t5 = torch.randn(3, 4)
print(t5)

tensor([[ 0.4439, -0.6788, -0.0318, -1.1451],
        [ 0.0899,  1.3824, -1.3845,  1.5218],
        [ 0.4876,  0.4127, -0.3019, -0.8704]])


In [25]:
print(t5.T.shape)

torch.Size([4, 3])


In [26]:
t = torch.arange(12).reshape(3, 4)
print(t.shape)

torch.Size([3, 4])


In [27]:
print(t)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [28]:
print(t[0])

tensor([0, 1, 2, 3])


In [29]:
print(t[:, 1])

tensor([1, 5, 9])


In [32]:
print(t[1:3, 0:2])

tensor([[4, 5],
        [8, 9]])


In [33]:
mask = t > 5
print(mask)

tensor([[False, False, False, False],
        [False, False,  True,  True],
        [ True,  True,  True,  True]])


In [34]:
print(t[mask])

tensor([ 6,  7,  8,  9, 10, 11])
