In [1]:
import torch
import numpy as np

In [2]:
np_arr = np.array([1.0, 2.0, 3.0])
print(np_arr)

[1. 2. 3.]


In [3]:
print(np_arr.dtype)

float64


In [4]:
tensor = torch.from_numpy(np_arr)

In [5]:
print(tensor)

tensor([1., 2., 3.], dtype=torch.float64)


In [6]:
tensor2 = torch.tensor([4.0, 5.0, 6.0])
print(tensor2)

tensor([4., 5., 6.])


In [7]:
np_arr2 = tensor2.numpy()
print(np_arr2)

[4. 5. 6.]


In [8]:
np_arr = np.array([1.0, 2.0, 3.0])
print(np_arr)

[1. 2. 3.]


In [9]:
tensor = torch.from_numpy(np_arr)
print(tensor)

tensor([1., 2., 3.], dtype=torch.float64)


In [10]:
tensor[0] = 99.0
print(tensor)

tensor([99.,  2.,  3.], dtype=torch.float64)


In [11]:
print(np_arr[0])

99.0


In [12]:
print(np_arr)

[99.  2.  3.]


In [13]:
print(np_arr)

[99.  2.  3.]


In [14]:
np_arr[1] = 88.0
print(np_arr)

[99. 88.  3.]


In [15]:
print(tensor)

tensor([99., 88.,  3.], dtype=torch.float64)


In [16]:
np_arr = np.array([1.0, 2.0, 3.0])
print(np_arr)

[1. 2. 3.]


In [17]:
tensor = torch.from_numpy(np_arr).clone()
tensor

tensor([1., 2., 3.], dtype=torch.float64)

In [18]:
tensor[0] = 99.0
tensor

tensor([99.,  2.,  3.], dtype=torch.float64)

In [19]:
print(np_arr)

[1. 2. 3.]


In [20]:
tensor2 = torch.tensor(np_arr)

In [21]:
tensor2

tensor([1., 2., 3.], dtype=torch.float64)

In [22]:
tensor2[0] = 100.0

In [23]:
tensor2

tensor([100.,   2.,   3.], dtype=torch.float64)

In [24]:
print(np_arr)

[1. 2. 3.]
