In [1]:
import torch

t1 = torch.tensor([1, 2, 3])
print(t1)

tensor([1, 2, 3])


In [2]:
print(t1.dtype)

torch.int64


In [3]:
t2 = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)
print(t2)

tensor([1., 2., 3.])


In [4]:
print(t2.dtype)

torch.float32


In [5]:
zeros = torch.zeros(2, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
print(zeros)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [8]:
ones = torch.ones(2, 3)
print(ones)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [9]:
like = torch.zeros_like(ones)
print(like)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [10]:
randn = torch.randn(2, 3)
print(randn)

tensor([[-0.1096, -1.1357,  1.0745],
        [ 0.0170,  0.6772, -1.9781]])


In [11]:
rand = torch.rand(2, 3)
print(rand)

tensor([[0.0718, 0.4311, 0.3353],
        [0.7298, 0.3108, 0.3472]])


In [12]:
randint = torch.randint(low=0, high=10, size=(2, 3))
print(randint)

tensor([[6, 1, 4],
        [1, 1, 1]])


In [13]:
arange = torch.arange(0, 10, step=2)

print(arange)

tensor([0, 2, 4, 6, 8])


In [14]:
linspace = torch.linspace(0, 1, steps=5)

print(linspace)

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


In [15]:
t = torch.randn(3, 4, 5)
print(t)

tensor([[[-0.5085,  1.6680,  0.8626,  0.6103, -0.4072],
         [-0.1868,  0.5789,  0.5598,  0.9540, -0.2338],
         [-1.2634, -0.5707,  0.2892,  0.5942,  0.9792],
         [ 0.7566,  1.8003, -1.4490, -0.6457, -0.2080]],

        [[-0.3250, -0.7019, -1.3745,  1.3334, -0.1244],
         [ 0.8430, -0.1103, -0.2927, -0.3505, -0.8356],
         [ 0.0046, -0.0468,  0.4837, -0.8392, -0.0988],
         [ 1.3006, -0.4721,  0.0572,  1.4391, -1.7860]],

        [[ 1.8746, -0.8410, -1.4936,  0.8147,  1.7215],
         [-0.4295,  0.9340,  1.7238,  1.5359,  0.5966],
         [ 0.4685,  0.3224, -0.7051, -0.2231, -0.9327],
         [-1.2647,  1.7677,  0.6706, -0.7112,  0.3721]]])


In [16]:
print(t.shape)

torch.Size([3, 4, 5])


In [17]:
print(t.ndim)

3


In [18]:
print(t.numel())

60
