In [1]:
import torch
from torch.nn.utils.rnn import pad_sequence

In [2]:
word2idx = {"<pad>": 0, "<unk>": 1, "我": 2, "喜欢": 3, "深度学习": 4, "很": 5, "有趣": 6}

In [3]:
word2idx

{'<pad>': 0, '<unk>': 1, '我': 2, '喜欢': 3, '深度学习': 4, '很': 5, '有趣': 6}

In [4]:
encoded = [
    torch.tensor([2, 3, 4]),  # "我 喜欢 深度学习"
    torch.tensor([4, 5, 6]),  # "深度学习 很 有趣"
    torch.tensor([2, 3, 6, 4]),  # "我 喜欢 有趣 深度学习"
]

In [5]:
encoded

[tensor([2, 3, 4]), tensor([4, 5, 6]), tensor([2, 3, 6, 4])]

In [6]:
padded = pad_sequence(encoded, batch_first=True, padding_value=0)

In [7]:
padded

tensor([[2, 3, 4, 0],
        [4, 5, 6, 0],
        [2, 3, 6, 4]])

In [8]:
print(f"形状: {padded.shape}")

形状: torch.Size([3, 4])


In [9]:
lengths = torch.tensor([len(s) for s in encoded])

In [10]:
lengths

tensor([3, 3, 4])

In [11]:
print(f"真实长度: {lengths}")

真实长度: tensor([3, 3, 4])


In [12]:
from torch.nn.utils.rnn import pack_padded_sequence

In [13]:
sorted_indices = lengths.argsort(descending=True)
sorted_indices

tensor([2, 0, 1])

In [14]:
padded

tensor([[2, 3, 4, 0],
        [4, 5, 6, 0],
        [2, 3, 6, 4]])

In [15]:
sorted_padded = padded[sorted_indices]

In [17]:
sorted_padded

tensor([[2, 3, 6, 4],
        [2, 3, 4, 0],
        [4, 5, 6, 0]])

In [18]:
sorted_lengths = lengths[sorted_indices]

In [19]:
sorted_lengths

tensor([4, 3, 3])

In [20]:
packed = pack_padded_sequence(sorted_padded, sorted_lengths.cpu(), batch_first=True)
packed

PackedSequence(data=tensor([2, 2, 4, 3, 3, 5, 6, 4, 6, 4]), batch_sizes=tensor([3, 3, 3, 1]), sorted_indices=None, unsorted_indices=None)

In [21]:
print(f"packed 类型: {type(packed)}")

packed 类型: <class 'torch.nn.utils.rnn.PackedSequence'>
