In [1]:
import numpy as np

In [2]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [3]:
print(arr_2d.ndim)

2


In [4]:
print(arr_2d.shape)

(2, 3)


In [5]:
print(arr_2d.size)

6


In [6]:
print(arr_2d.dtype)

int64


In [7]:
print(arr_2d.itemsize)

8


In [8]:
print(arr_2d.nbytes)

48


In [9]:
arr_3d = np.array([[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]]])
print(arr_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [10]:
print(arr_3d.ndim)

3


In [11]:
print(arr_3d.shape)

(2, 3, 2)


In [12]:
print(arr_3d.size)

12
