In [1]:
import numpy as np

In [2]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

In [3]:
print(arr1)

[[1 2 3]
 [4 5 6]]


In [4]:
print(arr2)

[[ 7  8  9]
 [10 11 12]]


In [5]:
print(arr1 + arr2)

[[ 8 10 12]
 [14 16 18]]


In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 2

In [7]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [8]:
print(arr.shape)

(2, 3)


In [9]:
res1 = arr * scalar
print(res1)

[[ 2  4  6]
 [ 8 10 12]]


In [10]:
arr_1d = np.array([10, 20, 30])
print(arr_1d)

[10 20 30]


In [11]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [12]:
print(arr_1d.shape)

(3,)


In [13]:
print(arr.shape)

(2, 3)


In [14]:
# [[10 20 30]
#  [10 20 30]]
print(arr + arr_1d)

[[11 22 33]
 [14 25 36]]


In [15]:
arr_2d_1 = np.array([[10], [20]])
print(arr_2d_1)

[[10]
 [20]]


In [16]:
print(arr_2d_1.shape)

(2, 1)


In [19]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [17]:
print(arr.shape)

(2, 3)


In [18]:
# [
#     [10][10][10]
#     [20][20][20]
# ]
print(arr * arr_2d_1)

[[ 10  20  30]
 [ 80 100 120]]


In [20]:
arr_error = np.array([[1, 2], [3, 4], [5, 6]])
print(arr_error.shape)

(3, 2)


In [21]:
print(arr.shape)

(2, 3)


In [22]:
print(arr + arr_error)

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 