In [1]:
import numpy as np

In [2]:
arr1 = np.ones((2, 3))
arr2 = np.ones(2)

In [3]:
print(arr1)

[[1. 1. 1.]
 [1. 1. 1.]]


In [4]:
print(arr2)

[1. 1.]


In [5]:
print(arr2.shape)

(2,)


In [6]:
print(arr1.shape)

(2, 3)


In [7]:
print(arr1 + arr2)

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [8]:
arr2_fix = arr2.reshape(2, 1)
print(arr2_fix.shape)

(2, 1)


In [9]:
print(arr2_fix + arr1)

[[2. 2. 2.]
 [2. 2. 2.]]


In [10]:
arr_mat1 = np.ones((2, 3))
arr_mat2 = np.ones((1, 3))
print(arr_mat1 + arr_mat2)

[[2. 2. 2.]
 [2. 2. 2.]]


In [11]:
print(arr_mat1 @ arr_mat2)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 3)

In [12]:
res_mat_mul = arr_mat1 @ arr_mat2.T
print(res_mat_mul)

[[3.]
 [3.]]


In [13]:
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
arr4 = np.array([10, 20])

In [14]:
print(arr3)

[[1 2 3]
 [4 5 6]]


In [15]:
print(arr4)

[10 20]


In [16]:
print(arr3.shape)
print(arr4.shape)

(2, 3)
(2,)


In [17]:
print(arr3 + arr4)

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [18]:
arr4_fix = arr4.reshape(2, 1)
res3 = arr3 * arr4_fix
print(res3)

[[ 10  20  30]
 [ 80 100 120]]
