In [3]:
import numpy as np

In [4]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [5]:
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [6]:
print(arr_2d.shape)

(2, 3)


In [7]:
print(arr_3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [8]:
print(arr_3d.shape)

(2, 2, 2)


In [9]:
res1_2d = arr_2d + 10
print(res1_2d)

[[11 12 13]
 [14 15 16]]


In [10]:
res2_3d = arr_3d * 2
print(res2_3d)

[[[ 2  4]
  [ 6  8]]

 [[10 12]
  [14 16]]]


In [11]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
arr_1d_col = np.array([10, 20, 30])
print(arr_1d_col)

[10 20 30]


In [13]:
print(arr_2d.shape)

(3, 3)


In [14]:
print(arr_1d_col.shape)

(3,)


In [15]:
# [10 20 30]
# [10 20 30]
# [10 20 30]
res2_col = arr_2d + arr_1d_col
print(res2_col)

[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [16]:
arr_1d_row = np.array([10, 20, 30]).reshape(3, 1)
print(arr_1d_row)

[[10]
 [20]
 [30]]


In [17]:
print(arr_1d_row.shape)

(3, 1)


In [18]:
# [10][10][10]
# [20][20][20]
# [30][30][30]
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
print(arr_2d * arr_1d_row)

[[ 10  20  30]
 [ 80 100 120]
 [210 240 270]]


In [20]:
arr_a = np.array([[[1], [2]], [[3], [4]]])
arr_b = np.array([[[10, 20], [30, 40]]])
print(arr_a)

[[[1]
  [2]]

 [[3]
  [4]]]


In [21]:
print(arr_b)

[[[10 20]
  [30 40]]]


In [22]:
print(arr_a.shape)

(2, 2, 1)


In [23]:
print(arr_b.shape)

(1, 2, 2)


In [24]:
print(arr_a + arr_b)

[[[11 21]
  [32 42]]

 [[13 23]
  [34 44]]]


In [25]:
arr1 = np.ones((2, 3))
arr2 = np.ones((3, 2))
print(arr1 + arr2)

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [26]:
arr3 = np.ones((3, 4, 2))
arr4 = np.ones((4, 3))  # (1, 4, 3)
print(arr3 + arr4)

ValueError: operands could not be broadcast together with shapes (3,4,2) (4,3) 

In [27]:
arr4_fix = np.ones((4, 1))
print(arr3 + arr4_fix)

[[[2. 2.]
  [2. 2.]
  [2. 2.]
  [2. 2.]]

 [[2. 2.]
  [2. 2.]
  [2. 2.]
  [2. 2.]]

 [[2. 2.]
  [2. 2.]
  [2. 2.]
  [2. 2.]]]
