In [1]:
import torch
import torch.nn as nn
import torch.optim as optim

In [2]:
model = nn.Linear(784, 10)

In [3]:
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [4]:
x = torch.randn(32, 784)

In [5]:
x

tensor([[ 0.8470,  1.9300,  0.1671,  ..., -1.4492, -0.7773, -0.3866],
        [-0.4027, -1.5112, -1.1413,  ..., -0.9401, -0.6436,  0.0436],
        [-1.8095, -0.1177,  0.1553,  ...,  1.4530,  2.5992, -0.5317],
        ...,
        [ 0.9741, -0.5443,  0.0827,  ...,  0.1106,  0.0335, -0.4997],
        [-0.7802,  3.0931,  0.5187,  ...,  1.0856,  0.3569, -2.5563],
        [-0.5096,  0.9476,  1.1519,  ...,  1.8025, -1.7359, -1.5801]])

In [6]:
labels = torch.randint(0, 10, (32,))

labels

tensor([0, 1, 8, 0, 0, 1, 5, 6, 6, 5, 6, 3, 4, 1, 3, 9, 3, 8, 1, 8, 3, 3, 5, 0,
        1, 4, 2, 8, 8, 9, 6, 3])

In [7]:
logits = model(x)

In [8]:
logits

tensor([[-0.4376, -0.0240,  0.6921,  0.4157, -0.2217,  0.5773, -0.0475,  0.1089,
          0.2495, -0.4867],
        [-0.0261, -0.5718, -0.2588,  0.0551, -0.3466, -0.5040,  0.2472, -0.1295,
         -0.3275, -0.8518],
        [ 0.3799, -0.7886, -0.3819,  1.2385, -1.6452,  0.1657,  1.5765,  0.4671,
         -1.4613,  0.9088],
        [-0.0371,  0.7662,  0.5070,  0.2078, -0.3687,  0.1717, -0.3589,  0.1811,
          0.2609, -0.3140],
        [ 0.6211, -0.1571, -0.5423,  0.2634,  0.3140,  0.5311,  0.1574,  0.2514,
         -0.3373,  0.0801],
        [ 0.6900, -0.7197,  0.0148,  0.5177, -0.4941,  0.4091, -0.2878, -0.2041,
         -0.7430, -0.4078],
        [ 0.5302, -0.1676, -0.0180, -0.1950,  0.7468, -0.0496,  0.2954, -0.7252,
         -0.2752,  0.5261],
        [-0.9766, -0.2883, -0.1002,  0.5257, -0.2440,  0.5334, -0.5019, -0.2637,
          1.4471,  0.1424],
        [-1.1147, -1.0090,  0.1659,  0.6090, -0.9711,  0.0510,  0.3935, -0.2031,
          0.4007, -0.5571],
        [-0.2954, -

In [9]:
loss = nn.CrossEntropyLoss()(logits, labels)

In [10]:
loss

tensor(2.4837, grad_fn=<NllLossBackward0>)

In [11]:
loss.backward()

In [12]:
optimizer.step()

In [13]:
optimizer.zero_grad()

In [14]:
print(f"SGD 更新完成，loss: {loss.item():.4f}")

SGD 更新完成，loss: 2.4837


In [15]:
optimizer = optim.Adam(model.parameters(), lr=1e-3)

logits = model(x)
loss = nn.CrossEntropyLoss()(logits, labels)
loss

tensor(2.2595, grad_fn=<NllLossBackward0>)

In [17]:
loss.backward()

In [18]:
optimizer.step()

In [19]:
optimizer.zero_grad()

In [20]:
print(f"Adam 更新完成，loss: {loss.item():.4f}")

Adam 更新完成，loss: 2.2595
