In [10]:
import torch
import torch.nn as nn

In [11]:
criterion = nn.CrossEntropyLoss()

In [12]:
logits = torch.randn(4, 10)
logits

tensor([[-0.0974, -0.6061,  1.6120,  0.6192,  1.8803,  0.5910, -2.2102,  0.4180,
          0.0344,  1.1449],
        [ 1.5817,  1.3796, -0.5364, -0.5965, -1.0513,  0.0442, -0.1898, -0.8182,
         -0.9941,  0.6586],
        [ 0.0820,  0.8898,  1.2998, -0.0947, -0.4497, -0.0594, -2.4693, -0.6894,
         -0.3640, -0.7305],
        [-1.0166, -0.1152, -0.5573, -1.4784,  0.5620, -0.6929,  1.3269, -1.3769,
         -0.9228, -0.5947]])

In [13]:
labels = torch.tensor([2, 0, 5, 8])

In [14]:
labels

tensor([2, 0, 5, 8])

In [15]:
loss = criterion(logits, labels)

In [16]:
print(f"分类损失: {loss.item():.4f}")

分类损失: 2.0676


In [17]:
criterion = nn.MSELoss()

predictions = torch.randn(4, 1)
predictions

tensor([[-0.5870],
        [ 0.2111],
        [ 0.3719],
        [-0.8111]])

In [18]:
targets = torch.randn(4, 1)
targets

tensor([[-0.1766],
        [ 0.4111],
        [ 0.1773],
        [ 0.0967]])

In [19]:
loss = criterion(predictions, targets)

In [20]:
print(f"回归损失: {loss.item():.4f}")

回归损失: 0.2676
