In [4]:
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
import numpy as np

In [5]:
X, y = load_iris(return_X_y=True)

In [6]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [7]:
model = LogisticRegression(max_iter=200, random_state=42)

scores_4d = cross_val_score(model, X_scaled, y, cv=5, scoring='accuracy')

In [8]:
scores_4d

array([0.96666667, 1.        , 0.93333333, 0.9       , 1.        ])

In [9]:
pca_2d = PCA(n_components=2)

X_pca_2d = pca_2d.fit_transform(X_scaled)
scores_2d = cross_val_score(model, X_pca_2d, y, cv=5, scoring='accuracy')

In [10]:
scores_2d

array([0.86666667, 0.96666667, 0.83333333, 0.93333333, 0.96666667])

In [11]:
pca_3d = PCA(n_components=3)
X_pca_3d = pca_3d.fit_transform(X_scaled)
scores_3d = cross_val_score(model, X_pca_3d, y, cv=5, scoring='accuracy')

In [12]:
scores_3d

array([0.96666667, 1.        , 0.93333333, 0.9       , 1.        ])

In [13]:
print("=" * 45)
print(f"{'方案':<20} {'维度':<6} {'准确率':<12} {'方差'}")
print("=" * 45)
print(f"{'原始数据':<20} {'4D':<6} {scores_4d.mean():.4f} ± {scores_4d.std():.4f}")
print(f"{'PCA 降到 3 维':<20} {'3D':<6} {scores_3d.mean():.4f} ± {scores_3d.std():.4f}")
print(f"{'PCA 降到 2 维':<20} {'2D':<6} {scores_2d.mean():.4f} ± {scores_2d.std():.4f}")
print("=" * 45)

方案                   维度     准确率          方差
原始数据                 4D     0.9600 ± 0.0389
PCA 降到 3 维           3D     0.9600 ± 0.0389
PCA 降到 2 维           2D     0.9133 ± 0.0542


In [14]:
print(f"\nPCA(2D) 累计解释方差比: {pca_2d.explained_variance_ratio_.sum():.4f}")
print(f"PCA(3D) 累计解释方差比: {pca_3d.explained_variance_ratio_.sum():.4f}")


PCA(2D) 累计解释方差比: 0.9581
PCA(3D) 累计解释方差比: 0.9948
