In [1]:
import numpy as np

In [3]:
score_list = [85, 92, 78, 90, 88, 76]
score_arr = np.array(score_list)

print(score_list)
print(score_arr)
print(type(score_list))
print(type(score_arr))

[85, 92, 78, 90, 88, 76]
[85 92 78 90 88 76]
<class 'list'>
<class 'numpy.ndarray'>


In [6]:
zero_arr = np.zeros((3, 2))
print(zero_arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [7]:
one_arr = np.ones((2, 3))
print(one_arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
range_arr1 = np.arange(10)
range_arr2 = np.arange(2, 10, 2)

In [9]:
print(range_arr1)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
print(range_arr2)

[2 4 6 8]


In [11]:
print(score_arr.shape)

(6,)


In [12]:
print(score_arr.ndim)

1


In [13]:
print(zero_arr.ndim)
print(one_arr.ndim)

2
2


In [14]:
print(score_arr.size)

6


In [15]:
print(range_arr2.size)

4


In [16]:
print(score_arr.dtype)

int32


In [17]:
print(one_arr.dtype)

float64


In [18]:
print(zero_arr.dtype)

float64


In [19]:
arr1 = np.arange(6)
print(arr1)

[0 1 2 3 4 5]


In [20]:
arr2 = arr1.reshape((2, 3))
print(arr2)

[[0 1 2]
 [3 4 5]]


In [21]:
arr3 = arr2.reshape((-1,))
print(arr3)

[0 1 2 3 4 5]


In [22]:
arr4 = arr2.flatten()
print(arr4)

[0 1 2 3 4 5]


In [23]:
arr5 = arr4.reshape((2, 2))
print(arr5)

ValueError: cannot reshape array of size 6 into shape (2,2)

In [24]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [25]:
print(arr[3])

3


In [26]:
print(arr[2: 7])
print(arr[::2])

[2 3 4 5 6]
[0 2 4 6 8]


In [27]:
arr_2d = np.arange(6).reshape((2, 3))
print(arr_2d)

[[0 1 2]
 [3 4 5]]


In [28]:
print(arr_2d[0, 1])

1


In [29]:
print(arr_2d[0, :])

[0 1 2]


In [30]:
print(arr_2d[:, 1])

[1 4]


In [31]:
score_arr = np.array([85, 92, 78, 90, 88])
print(score_arr)

[85 92 78 90 88]


In [32]:
score_add = score_arr + 5
print(score_add)

[90 97 83 95 93]


In [33]:
score_mul = score_arr * 0.8
print(score_mul)

[68.  73.6 62.4 72.  70.4]


In [34]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

In [35]:
print(arr1 + arr2)

[ 7  9 11 13 15]


In [36]:
print(arr1 * arr2)

[ 6 14 24 36 50]


In [37]:
score_arr = np.array([85, 92, 78, 90, 88, 76, 95, 82])
print(score_arr)

[85 92 78 90 88 76 95 82]


In [38]:
print(np.sum(score_arr))

686


In [39]:
print(np.mean(score_arr))

85.75


In [40]:
print(score_arr.mean())

85.75


In [41]:
print(score_arr.max())
print(score_arr.min())

95
76


In [42]:
print(np.max(score_arr))
print(np.min(score_arr))

95
76


In [44]:
median = np.median(score_arr)
print(median)

86.5


In [45]:
print(np.std(score_arr))

6.299801584177076


In [46]:
print(np.argmax(score_arr))
print(np.argmin(score_arr))

6
5
