In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [3]:
num = 2
print(num)

2


In [4]:
print(arr + num)

[3 4 5 6 7]


In [5]:
print(arr - num)

[-1  0  1  2  3]


In [6]:
print(arr * num)

[ 2  4  6  8 10]


In [7]:
print(arr / num)

[0.5 1.  1.5 2.  2.5]


In [8]:
print(arr ** num)

[ 1  4  9 16 25]


In [9]:
print(arr // num)

[0 1 1 2 2]


In [10]:
print(arr % num)

[1 0 1 0 1]


In [11]:
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [12]:
print(10 - arr)

[9 8 7]


In [13]:
print(2 * arr)

[2 4 6]


In [14]:
new_arr = arr + 2
print(new_arr)
print(arr)

[3 4 5]
[1 2 3]
