In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

print(arr1)
print(arr2)

[1 2 3 4]
[5 6 7 8]


In [3]:
print(arr1 + arr2)

[ 6  8 10 12]


In [4]:
print(arr1 - arr2)

[-4 -4 -4 -4]


In [5]:
print(arr1 * arr2)

[ 5 12 21 32]


In [6]:
print(arr1 / arr2)

[0.2        0.33333333 0.42857143 0.5       ]


In [7]:
print(arr1 ** arr2)

[    1    64  2187 65536]


In [8]:
print(arr1 // arr2)

[0 0 0 0]


In [9]:
print(arr1 % arr2)

[1 2 3 4]


In [10]:
print(arr1.shape)
print(arr2.shape)

(4,)
(4,)


In [11]:
arr1 = np.array([1, 3, 5, 7])
arr2 = np.array([2, 3, 4, 8])
print(arr1)
print(arr2)

[1 3 5 7]
[2 3 4 8]


In [12]:
print(arr1 == arr2)

[False  True False False]


In [13]:
print(arr1 > arr2)

[False False  True False]
