In [1]:
import numpy as np

In [2]:
arr = np.array([[1.0, np.nan, 3.0], [4.0, np.nan, 5.0], [7.0, 8.0, 9.0]])
print(arr)

[[ 1. nan  3.]
 [ 4. nan  5.]
 [ 7.  8.  9.]]


In [3]:
arr_fill_0 = arr.copy()
print(arr_fill_0)

[[ 1. nan  3.]
 [ 4. nan  5.]
 [ 7.  8.  9.]]


In [4]:
arr_fill_0[np.isnan(arr_fill_0)] = 0
print(arr_fill_0)

[[1. 0. 3.]
 [4. 0. 5.]
 [7. 8. 9.]]


In [5]:
print(arr)

[[ 1. nan  3.]
 [ 4. nan  5.]
 [ 7.  8.  9.]]


In [6]:
arr_fill_mean = arr.copy()
print(arr_fill_mean)

[[ 1. nan  3.]
 [ 4. nan  5.]
 [ 7.  8.  9.]]


In [7]:
col_means = np.nanmean(arr_fill_mean, axis=0)
print(col_means)

[4.         8.         5.66666667]


In [8]:
for i in range(arr_fill_mean.shape[1]):
    arr_fill_mean[np.isnan(arr_fill_mean[:, i]), i] = col_means[i]

print(arr_fill_mean)

[[1. 8. 3.]
 [4. 8. 5.]
 [7. 8. 9.]]


In [9]:
arr_fill_row = arr.copy()
print(arr_fill_row)

[[ 1. nan  3.]
 [ 4. nan  5.]
 [ 7.  8.  9.]]


In [10]:
row_means = np.nanmean(arr_fill_row, axis=1)
print(row_means)

[2.  4.5 8. ]


In [11]:
for i in range(arr_fill_row.shape[0]):
    arr_fill_row[i, np.isnan(arr_fill_row[i])] = row_means[i]

print(arr_fill_row)

[[1.  2.  3. ]
 [4.  4.5 5. ]
 [7.  8.  9. ]]


In [12]:
arr = np.array([[1.0, np.nan, 3.0], [4.0, 5.0, 6.0], [7.0, np.nan, 9.0]])
print(arr)

[[ 1. nan  3.]
 [ 4.  5.  6.]
 [ 7. nan  9.]]


In [13]:
arr_del_row = arr[~np.isnan(arr).any(axis=1)]
print(arr_del_row)

[[4. 5. 6.]]


In [14]:
print(arr[:, ~np.isnan(arr).any(axis=0)])

[[1. 3.]
 [4. 6.]
 [7. 9.]]


In [15]:
arr_full_nan = np.array([[np.nan, np.nan], [1.0, 2.0]])
print(arr_full_nan)

[[nan nan]
 [ 1.  2.]]


In [16]:
arr_del_full_row = arr_full_nan[~np.all(np.isnan(arr_full_nan), axis=1)]
print(arr_del_full_row)

[[1. 2.]]
