In [1]:
import numpy as np

In [2]:
arr = np.array([[1.0, 2.0, np.nan], [4.0, np.nan, 6.0], [7.0, 8.0, 9.0]])
print(arr)

[[ 1.  2. nan]
 [ 4. nan  6.]
 [ 7.  8.  9.]]


In [3]:
print(arr.sum())

nan


In [4]:
print(arr.mean())

nan


In [5]:
print(arr.max())

nan


In [6]:
print(arr.min())

nan


In [7]:
print(arr)

[[ 1.  2. nan]
 [ 4. nan  6.]
 [ 7.  8.  9.]]


In [8]:
print(np.nansum(arr))

37.0


In [9]:
print(np.nanmean(arr))

5.285714285714286


In [10]:
print(np.nanmax(arr))

9.0


In [11]:
print(np.nanmin(arr))

1.0


In [12]:
print(arr)

[[ 1.  2. nan]
 [ 4. nan  6.]
 [ 7.  8.  9.]]


In [13]:
print(np.nanmean(arr, axis=0))

[4.  5.  7.5]


In [14]:
print(np.nansum(arr, axis=1))

[ 3. 10. 24.]


In [15]:
arr = np.array([[1.0, np.nan, 3.0], [np.nan, 5.0, np.nan], [7.0, 8.0, 9.0]])
print(arr)

[[ 1. nan  3.]
 [nan  5. nan]
 [ 7.  8.  9.]]


In [16]:
print(np.isnan(arr).sum())

3


In [17]:
print(np.isnan(arr).sum(axis=0))

[1 1 1]


In [18]:
print(np.isnan(arr).sum() / arr.size)

0.3333333333333333


In [19]:
print(arr[np.isfinite(arr)].mean())

5.5
