In [1]:
import numpy as np

In [2]:
arr = np.array([[1.0, 2.0, np.nan], [4.0, np.nan, 6.0], [7.0, 8.0, 9.0]])
print(arr)

[[ 1.  2. nan]
 [ 4. nan  6.]
 [ 7.  8.  9.]]


In [3]:
print(arr.sum())

nan


In [4]:
print(arr.mean())

nan


In [5]:
print(arr.max())

nan


In [6]:
print(arr.min())

nan


In [7]:
print(np.nansum(arr))

37.0


In [8]:
print(np.nanmean(arr))

5.285714285714286


In [9]:
print(np.nanmax(arr))

9.0


In [10]:
print(np.nanmin(arr))

1.0


In [11]:
print(arr)

[[ 1.  2. nan]
 [ 4. nan  6.]
 [ 7.  8.  9.]]


In [12]:
print(np.nanmean(arr, axis=0))

[4.  5.  7.5]


In [13]:
print(np.nansum(arr, axis=1))

[ 3. 10. 24.]


In [14]:
arr = np.array([[1.0, np.nan, 3.0], [np.nan, 5.0, np.nan], [7.0, 8.0, 9.0]])
print(arr)

[[ 1. nan  3.]
 [nan  5. nan]
 [ 7.  8.  9.]]


In [16]:
nan_total = np.isnan(arr).sum()
print(nan_total)

3


In [17]:
nan_col = np.isnan(arr).sum(axis=0)
print(nan_col)

[1 1 1]


In [18]:
print(np.isnan(arr).sum(axis=1))

[1 2 0]


In [19]:
nan_ratio = np.isnan(arr).sum() / arr.size
print(nan_ratio)

0.3333333333333333


In [20]:
valid_vals = arr[np.isfinite(arr)]
print(valid_vals)

[1. 3. 5. 7. 8. 9.]


In [21]:
print(valid_vals.mean())

5.5
