In [1]:
import numpy as np

In [2]:
arr_float = np.array([[1.0, 2.0, np.nan], [4.0, np.nan, 6.0]])
print(arr_float)

[[ 1.  2. nan]
 [ 4. nan  6.]]


In [3]:
arr_int = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_int)

[[1 2 3]
 [4 5 6]]


In [4]:
print(arr_int.dtype)

int64


In [5]:
arr_int[1, 1] = np.nan
print(arr_int)

ValueError: cannot convert float NaN to integer

In [6]:
arr_int_float = arr_int.astype(float)
print(arr_int_float)

[[1. 2. 3.]
 [4. 5. 6.]]


In [7]:
arr_int_float[1, 1] = np.nan
print(arr_int_float)

[[ 1.  2.  3.]
 [ 4. nan  6.]]


In [8]:
print(arr_float)

[[ 1.  2. nan]
 [ 4. nan  6.]]


In [9]:
print(arr_float == np.nan)

[[False False False]
 [False False False]]


In [10]:
arr = np.array([[1.0, np.nan, 3.0], [np.inf, 5.0, -np.inf]])
print(arr)

[[  1.  nan   3.]
 [ inf   5. -inf]]


In [11]:
nan_mask = np.isnan(arr)
print(nan_mask)

[[False  True False]
 [False False False]]


In [12]:
inf_mask = np.isinf(arr)
print(inf_mask)

[[False False False]
 [ True False  True]]


In [13]:
valid_mask = np.isfinite(arr)
print(valid_mask)

[[ True False  True]
 [False  True False]]


In [14]:
print(arr)

[[  1.  nan   3.]
 [ inf   5. -inf]]


In [15]:
nan_count = np.isnan(arr).sum()
print(nan_count)

1
