In [1]:
import numpy as np

In [4]:
arr_1d = np.array([3, 1, 4, 1, 5, 9, 5, 3])
arr_2d = np.array([[1, 2, 2], [3, 3, 1]])
print(arr_1d)

[3 1 4 1 5 9 5 3]


In [5]:
print(arr_2d)

[[1 2 2]
 [3 3 1]]


In [6]:
unique_vals = np.unique(arr_1d)
print(unique_vals)

[1 3 4 5 9]


In [7]:
unique_vals, counts = np.unique(arr_1d, return_counts=True)
print(unique_vals)

[1 3 4 5 9]


In [8]:
print(counts)

[2 2 1 2 1]


In [9]:
print(list(zip(unique_vals, counts)))

[(np.int64(1), np.int64(2)), (np.int64(3), np.int64(2)), (np.int64(4), np.int64(1)), (np.int64(5), np.int64(2)), (np.int64(9), np.int64(1))]


In [10]:
print(arr_1d)

[3 1 4 1 5 9 5 3]


In [11]:
unique_vals, index = np.unique(arr_1d, return_index=True)
print(unique_vals)

[1 3 4 5 9]


In [12]:
print(index)

[1 0 2 4 5]


In [13]:
print(arr_2d)

[[1 2 2]
 [3 3 1]]


In [14]:
unique_2d = np.unique(arr_2d)
print(unique_2d)

[1 2 3]


In [15]:
print(arr_1d)

[3 1 4 1 5 9 5 3]


In [16]:
mask = np.in1d(arr_1d, [1, 3, 5], invert=True)

AttributeError: module 'numpy' has no attribute 'in1d'

In [17]:
print(arr_1d)

[3 1 4 1 5 9 5 3]


In [18]:
mask = np.isin(arr_1d, [1, 3, 5], invert=True)
print(mask)

[False False  True False False  True False False]


In [19]:
filtered = arr_1d[mask]
print(filtered)

[4 9]


In [20]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([3, 4, 5, 6, 7])
print(arr1)

[1 2 3 4 5]


In [21]:
print(arr2)

[3 4 5 6 7]


In [22]:
diff = np.setdiff1d(arr1, arr2)
print(diff)

[1 2]


In [23]:
intersect = np.intersect1d(arr1, arr2)
print(intersect)

[3 4 5]


In [24]:
arr = np.array([3, 1, 4, 1, 5, 9, 5, 3])
print(arr)

[3 1 4 1 5 9 5 3]


In [25]:
_, index = np.unique(arr, return_index=True)
unique_keep_order = arr[np.sort(index)]
print(unique_keep_order)

[3 1 4 5 9]
