In [1]:
import numpy as np

In [2]:
arr_1d = np.array([3, 1, 4, 1, 5, 9])
arr_2d = np.array([[5, 2, 9], [1, 7, 3]])
print(arr_1d)

[3 1 4 1 5 9]


In [3]:
print(arr_2d)

[[5 2 9]
 [1 7 3]]


In [4]:
sorted_1d = np.sort(arr_1d)
print(sorted_1d)

[1 1 3 4 5 9]


In [5]:
print(arr_1d)

[3 1 4 1 5 9]


In [6]:
print(arr_2d)

[[5 2 9]
 [1 7 3]]


In [7]:
sorted_2d_row = np.sort(arr_2d, axis=1)
print(sorted_2d_row)

[[2 5 9]
 [1 3 7]]


In [8]:
sorted_2d_col = np.sort(arr_2d, axis=0)
print(sorted_2d_col)

[[1 2 3]
 [5 7 9]]


In [9]:
print(arr_2d)

[[5 2 9]
 [1 7 3]]


In [10]:
arr_1d_copy = arr_1d.copy()
print(arr_1d_copy)

[3 1 4 1 5 9]


In [11]:
arr_1d_copy.sort()

In [12]:
print(arr_1d_copy)

[1 1 3 4 5 9]


In [13]:
print(arr_1d)

[3 1 4 1 5 9]


In [14]:
index = np.argsort(arr_1d)

In [15]:
print(index)

[1 3 0 2 4 5]


In [16]:
sorted_by_index = arr_1d[index]
print(sorted_by_index)

[1 1 3 4 5 9]


In [17]:
A = np.array([3, 1, 2])
B = np.array([10, 20, 30])
print(A)

[3 1 2]


In [18]:
print(B)

[10 20 30]


In [19]:
index_A = np.argsort(A)
print(index_A)

[1 2 0]


In [20]:
sorted_A = A[index_A]
print(sorted_A)

[1 2 3]


In [21]:
sorted_B = B[index_A]

In [22]:
print(sorted_B)

[20 30 10]
