In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])

In [3]:
mat_mul = np.linalg.multi_dot([A, B])
print(mat_mul)

[[19 22]
 [43 50]]


In [4]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [5]:
det_A = np.linalg.det(A)
print(det_A)

-2.0000000000000004


In [6]:
x = np.linalg.solve(A, v)
print(x)

[-8.   8.5]


In [7]:
eigenvals, eigenvecs = np.linalg.eig(A)
print(eigenvals)

[-0.37228132  5.37228132]


In [8]:
print(eigenvecs)

[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [10]:
print(A)

[[1 2]
 [3 4]]


In [9]:
A_T = A.T
print(A_T)

[[1 3]
 [2 4]]
