In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr)

[1 2 3 4 5 6 7 8]


In [4]:
# print(arr.median())
print(np.median(arr))

4.5


In [5]:
print(arr.median())

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [6]:
print(arr.cumsum())

[ 1  3  6 10 15 21 28 36]


In [7]:
print(arr.cumprod())

[    1     2     6    24   120   720  5040 40320]


In [10]:
print(np.percentile(arr, 50))

4.5


In [11]:
print(np.percentile(arr, 75))

6.25


In [12]:
print(arr.ptp())

AttributeError: 'numpy.ndarray' object has no attribute 'ptp'

In [13]:
print(np.ptp(arr))

7


In [18]:
arr = np.array([1, 2, 2, 3, 3, 3, 5])
arr_nan = np.array([1, np.nan, 3, 4])

print(arr)
print(arr_nan)

[1 2 2 3 3 3 5]
[ 1. nan  3.  4.]


In [19]:
print(arr.nonzero())

(array([0, 1, 2, 3, 4, 5, 6]),)


In [20]:
print(np.nanmean(arr_nan))

2.6666666666666665


In [21]:
print(np.nanmax(arr_nan))

4.0


In [22]:
print(np.nanmin(arr_nan))

1.0
