In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [3]:
print(arr.sum())

15


In [4]:
print(arr.sum(axis=None))

15


In [5]:
print(arr.mean(axis=None))

3.0


In [6]:
print(arr.mean())

3.0


In [7]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [8]:
res1 = arr.max(keepdims=False)
print(res1, type(res1))

5 <class 'numpy.int64'>


In [9]:
res2 = arr.max(keepdims=True)
print(res2, type(res2))

[5] <class 'numpy.ndarray'>


In [10]:
print(res2.shape)

(1,)


In [11]:
arr_nan = np.array([1, np.nan, 3, np.nan, 5])
print(arr_nan)

[ 1. nan  3. nan  5.]


In [12]:
print(arr_nan.sum())

nan


In [13]:
print(arr_nan.sum(skipna=True))

TypeError: _sum() got an unexpected keyword argument 'skipna'

In [14]:
print(np.nansum(arr_nan))

9.0


In [15]:
print(np.nanmean(arr_nan))

3.0


In [16]:
arr = np.array([1, 2, 3, 4, 5])
arr_nan = np.array([1, np.nan, 3, 4])
print(arr)
print(arr_nan)

[1 2 3 4 5]
[ 1. nan  3.  4.]


In [17]:
print(arr.sum())

15


In [18]:
print(arr_nan.mean())

nan


In [19]:
print(np.nanmean(arr_nan))

2.6666666666666665


In [20]:
print(arr.min(keepdims=True))

[1]
