In [1]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5, 5, 8])
print(arr)

[1 2 3 4 5 5 8]


In [4]:
print(arr.sum())

28


In [5]:
print(arr.mean())

4.0


In [6]:
print(arr.max())

8


In [7]:
print(arr.min())

1


In [8]:
print(arr.std())

2.138089935299395


In [9]:
print(arr.var())

4.571428571428571


In [10]:
print(arr.size)

7


In [11]:
print(arr)

[1 2 3 4 5 5 8]


In [12]:
print(arr.argmax())

6


In [13]:
print(arr.argmin())

0


In [14]:
arr = np.array([1, 2, 2, 3, 3, 3, 5])
print(arr)

[1 2 2 3 3 3 5]


In [15]:
print(np.unique(arr))

[1 2 3 5]
