##### 2.1.1 从 python 原生结构转换

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

[1 2 3 4 5]


In [3]:
arr2 = np.array((6, 7, 8, 9))
print(arr2)

[6 7 8 9]


In [4]:
arr3 = np.array(range(1, 6))
print(arr3)

[1 2 3 4 5]


In [5]:
arr1.ndim

1

In [6]:
arr1.dtype

dtype('int64')

In [7]:
arr1.shape

(5,)

In [8]:
arr1.size

5

In [9]:
arr4 = np.array([1, 2, "3"])
print(arr4)

['1' '2' '3']


In [10]:
arr5 = np.array([1.0, 2.0, 3.4])
print(arr5)

[1.  2.  3.4]


In [11]:
arr5.dtype

dtype('float64')

In [12]:
arr6 = np.array([1, 2, 3.4])
print(arr6)

[1.  2.  3.4]
