In [1]:
import numpy as np

In [3]:
print(np.array([1, 2, 3], dtype=float))

[1. 2. 3.]


In [4]:
print(np.zeros(4, dtype=int))

[0 0 0 0]


In [5]:
print(np.zeros(4))

[0. 0. 0. 0.]


In [11]:
print(np.random.randint(1, 5, 3, dtype=int))

[4 2 4]


In [12]:
arr_float = np.array([1.2, 2.9, -3.5])
arr_int = np.array([0, 1, -2])

print(arr_float)
print(arr_int)

[ 1.2  2.9 -3.5]
[ 0  1 -2]


In [13]:
arr_float.astype(int)

array([ 1,  2, -3])

In [14]:
arr_int.astype(float)

array([ 0.,  1., -2.])

In [15]:
arr_int.astype(bool)

array([False,  True,  True])

In [16]:
np.array([True, False]).astype(int)

array([1, 0])