In [1]:
import torch
import torch.nn as nn

In [2]:
class MLP(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, output_dim),
        )

    def forward(self, x):
        return self.net(x)

In [3]:
model = MLP(784, 256, 10)

In [4]:
x = torch.randn(8, 784)

In [5]:
x

tensor([[ 1.7231,  0.2529, -0.4926,  ..., -1.4048,  2.6114, -1.8008],
        [-0.0838,  0.2316,  0.3137,  ...,  2.0225,  0.7775,  1.5618],
        [-0.6229, -0.5950, -0.8986,  ..., -2.2930, -0.2479, -0.6820],
        ...,
        [-1.8587, -2.6665,  0.7038,  ...,  0.7123,  0.1048, -1.5135],
        [ 0.4564,  0.2139,  0.1602,  ...,  0.3013, -0.8171, -0.2734],
        [-0.2030, -1.1811,  0.5326,  ...,  1.4759,  0.7551,  0.4377]])

In [7]:
logits = model(x)

In [8]:
logits

tensor([[-0.1040,  0.2035, -0.1166, -0.0913,  0.1263,  0.0074, -0.0256, -0.1318,
          0.0633,  0.0908],
        [-0.0860,  0.1224,  0.0303,  0.0126,  0.1726,  0.1124, -0.0020, -0.0447,
          0.0067,  0.1063],
        [-0.0113,  0.1111, -0.0330, -0.1726,  0.0764, -0.0794,  0.0302, -0.1397,
          0.0437,  0.0907],
        [-0.0246,  0.2063, -0.0955, -0.1542,  0.1162,  0.1001, -0.0188, -0.1135,
         -0.0738,  0.0010],
        [-0.1347,  0.0953, -0.0205, -0.0765, -0.0335, -0.0499,  0.0209, -0.0982,
          0.0434, -0.0247],
        [ 0.1005,  0.1995, -0.0546, -0.1382,  0.0258,  0.0015, -0.0470, -0.2016,
         -0.1102,  0.0374],
        [-0.1050,  0.0255, -0.1579, -0.1235,  0.1281,  0.0003,  0.0354, -0.0560,
          0.1131, -0.1128],
        [-0.1550,  0.1516, -0.1236, -0.0661,  0.1168,  0.0928,  0.1409, -0.0606,
          0.0410, -0.0852]], grad_fn=<AddmmBackward0>)

In [9]:
print(f"输出形状: {logits.shape}")

输出形状: torch.Size([8, 10])


In [10]:
probs = torch.softmax(logits, dim=1)

In [11]:
probs

tensor([[0.0894, 0.1216, 0.0883, 0.0905, 0.1125, 0.0999, 0.0967, 0.0869, 0.1057,
         0.1086],
        [0.0876, 0.1079, 0.0984, 0.0967, 0.1135, 0.1069, 0.0953, 0.0913, 0.0961,
         0.1062],
        [0.0993, 0.1122, 0.0972, 0.0845, 0.1084, 0.0928, 0.1035, 0.0873, 0.1049,
         0.1100],
        [0.0975, 0.1229, 0.0909, 0.0857, 0.1123, 0.1105, 0.0981, 0.0892, 0.0929,
         0.1001],
        [0.0897, 0.1129, 0.1005, 0.0951, 0.0992, 0.0976, 0.1048, 0.0930, 0.1072,
         0.1001],
        [0.1119, 0.1236, 0.0959, 0.0882, 0.1039, 0.1014, 0.0966, 0.0828, 0.0907,
         0.1051],
        [0.0919, 0.1047, 0.0872, 0.0902, 0.1160, 0.1021, 0.1058, 0.0965, 0.1143,
         0.0912],
        [0.0847, 0.1151, 0.0874, 0.0926, 0.1111, 0.1085, 0.1138, 0.0931, 0.1030,
         0.0908]], grad_fn=<SoftmaxBackward0>)

In [12]:
print(f"概率和: {probs[0].sum().item():.4f}")

概率和: 1.0000
